var walletLanguages = {
    'en': {
        'lang-alias': 'English',
        'open-regular': 'Regular wallet',
        'open-key': 'Open by key',
        'disclaimer': 'This page uses javascript to generate your addresses and sign your transactions within your browser, this means we never receive your private keys, this can be independently verified by reviewing the source code on Github.',
        'open-reminder': '<b>Notice:</b> Please make sure that you remember your account details, otherwise you may lose access to your funds.',
        'open': 'Open',
        'home': 'Home',
        'broadcast': 'Broadcast',
        'settings': 'Settings',
        'email-address': 'Email or other text (min 3 chars)',
        'password': 'Password',
        'password-confirm': 'Confirm password',
        'wif-key': 'WIF Private key',
        'show': 'Show',
        'hide': 'Hide',
        'address': 'Address',
        'public-key': 'Public Key',
        'private-key': 'Private Key',
        'broadcast-transaction': 'Broadcast transaction',
        'enter-transaction': 'Enter your signed transaction',
        'address-type': 'Address Type',
        'wallet-backend': 'Wallet Backend',
        'update': 'Update',
        'version': 'Version:',
        'wallet': 'Wallet',
        'close': 'Close',
        'send': 'Send',
        'history': 'History',
        'keys': 'Keys',
        'reset': 'Reset',
        'available-balance': 'Available balance:',
        'enter-address': 'Enter address',
        'amount': 'Amount',
        'fee': 'Fee',
        'recommended': 'recommended',
        'loading': 'Loading...',
        'send-sure': 'Are you sure?',
        'send-processing': 'Processing...',
        'success': 'Success',
        'failed': 'Failed',
        'send-it': 'Yes, send it!',
        'cancel': 'Cancel',
        'send-warning': 'You are one step away from sending',
        'send-warning-reverse': 'This action <strong>cannot</strong> be reversed. Are you sure about this?',
        'loading-utxo': 'Loading UTXOs...',
        'transaction-creation': 'Creating transaction...',
        'transaction-broadcasted': 'Transaction successfully broadcasted: ',
        'address-type-changed': 'Address type changed to',
        'backend-switched': 'Backend is switched to',
        'backend-down': 'don\'t seems to be available',
        'wallet-api': 'Wallet API backend',
        'open-wallet': 'Open Wallet',
        'bad-utxo': 'Unsupported UTXO type!',
        'balance-load-failed': 'We couldn\'t load wallet balance!',
        'not-enough-funds': 'You don\'t have enough funds for this transaction!',
        'not-valid-address': 'You must specify valid address!',
        'not-valid-amount': 'You must specify valid amount!',
        'not-valid-fee': 'You must specify valid fee!',
        'bad-priv-key': 'Bad WIF private key!',
        'not-enough-utxo': 'Not enough UTXO :(',
        'broadcast-failed': 'Transaction broadcast failed :(',
        'pass-not-match': 'Your passwords do not match!',
        'pass-too-short': 'Your password must be at least 10 chars long!',
        'small-fee': 'You should specify fee not less than',
        'scan-qr': 'Scan',
        'scan-modal-title': 'QR Code scanner',
        'webcam-message': 'Please make sure you have a webcam enabled',
        'webcam-loading': 'Loading camera...',
        'outputs-added': 'added to outputs',
        'pin-login-title': 'Saved wallet found',
        'pin-login-placeholder': 'Enter PIN to open',
        'pin-login-btn': 'Open',
        'pin-login-error': 'Wrong PIN, try again.',
        'pin-login-forget': 'Forget saved wallet',
        'settings-forget-wallet': 'Forget saved wallet',
        'pin-title-default': 'Wallet PIN',
        'pin-input-placeholder': 'PIN (min 8 chars)',
        'pin-create-title': 'Create wallet PIN',
        'pin-create-desc': 'Choose a strong PIN (min 8 characters, with at least one uppercase, lowercase, digit and special character). You will use it every time you open the wallet.',
        'pin-confirm-title': 'Confirm PIN',
        'pin-confirm-desc': 'Re-enter your PIN to confirm.',
        'pin-too-short': 'PIN must be at least 8 characters',
        'pin-mismatch': 'PINs do not match. Try again.',
        'ok': 'OK',
        'coin-control': 'Coin Control',
        'coin-control-manual': 'Manual UTXO selection',
        'coin-control-select-all': 'Select all mature',
        'coin-control-confs': 'Confs',
        'coin-control-type': 'Type',
        'coin-control-status': 'Status',
        'coin-control-no-utxo': 'No UTXOs',
        'coin-control-mature': 'mature',
        'coin-control-coinbase': 'coinbase',
        'coin-control-regular': 'regular',
        'coin-control-matures-in': 'Matures in',
        'coin-control-blocks': 'blocks',
        'coin-control-immature-title': 'Immature coinbase — cannot spend',
        'coin-control-selected': 'selected',
        'immature-mining': 'Immature (mining):',
        'immature-cannot-spend': 'cannot spend yet',
        'unconfirmed-balance': 'Unconfirmed:',
        'unconfirmed-mempool': 'pending in mempool',
        'history-loading': 'Loading history…',
        'no-transactions': 'No transactions yet',
        'history-failed': 'Failed to load history',
        'history-network-error': 'Network error',
        'history-view-all': 'View all',
        'history-on-explorer': 'transactions on explorer',
        'history-conf': 'conf',
        'history-confirmed': 'confirmed',
        'history-pending': 'pending',
        'copy-address': 'Copy address',
        'wallet-saved': 'Wallet saved. Next time just enter your PIN.',
        'wallet-deleted': 'Saved wallet deleted.',
        'identity-too-short': 'Identity must be at least 3 characters.',
        'auto-locked': 'Wallet locked due to inactivity.',
        'theme-light': '☀️ Light',
        'theme-dark': '🌙 Dark',
        'theme-auto': '🔄 Auto',
        'redeem-script': 'Redeem Script (SegWit)',
        'open-seed': '🌱 Seed Phrase',
        'seed-btn-create': '✨ Create New Wallet',
        'seed-btn-restore': '🔑 Restore from Seed Phrase',
        'seed-step1-label': 'Step 1 of 2 — Your Seed Phrase',
        'seed-write-warning': '⚠️ Write these words down in order and store them safely. Anyone with these words controls your funds.',
        'seed-print': 'Save PNG',
        'seed-next': 'Next →',
        'seed-step2-label': 'Step 2 of 2 — Verify Seed Phrase',
        'seed-verify-desc': 'Enter the words at these positions to confirm you saved them correctly:',
        'seed-verify-error-msg': 'Incorrect words. Please check your phrase.',
        'seed-confirm-pin': 'Confirm &amp; Set PIN',
        'seed-restore-title': 'Restore from Seed Phrase',
        'seed-word-count': 'Word count:',
        'seed-restore-placeholder': 'Enter your seed phrase words separated by spaces…',
        'seed-advanced': 'Advanced ▼',
        'seed-deriv-path': 'Derivation path',
        'seed-deriv-hint': 'Default: BIP84 native SegWit. Change for Electrum/Ledger compatibility.',
        'seed-restore-btn': 'Restore &amp; Set PIN',
        'seed-backup-label': 'Seed Phrase Backup',
        'seed-show-btn': '🌱 Show Seed Phrase (requires PIN or Passkey)',
        'seed-hide-btn': '🔒 Hide',
        'seed-word-num': 'Word',
        'seed-pin-modal-title': 'Enter PIN to view seed phrase',
        'seed-pin-modal-desc': 'Your seed phrase will be shown briefly.',
        'seed-pin-cancel':  'Due to cancellation, the seed has been regenerated for security.',
        'privkey-pin-desc': 'Enter PIN to reveal private key',
        'seed-count-mismatch': 'Expected {n} words, got {m}.',
        'seed-invalid-phrase': 'Invalid seed phrase. Check spelling and word order.',
        'seed-deriv-error': 'Derivation error:',
        'legacy-warn-password': '⚠️ <strong>Not recommended.</strong> This method derives a key from a password hash and is kept for backward compatibility only. Please migrate your funds to a Seed Phrase wallet.',
        'legacy-warn-key': '⚠️ <strong>Not recommended.</strong> Raw private key import is provided for compatibility only. Use a Seed Phrase wallet for better security and recoverability.',
        'seed-print-secret': 'Your Seed Phrase — Keep Secret!',
        'seed-print-warning': '⚠ Never share this image. Store it offline only.',
        'seed-path-label': 'Path:',
        'passkey-login-btn': 'Unlock with Passkey',
        'passkey-settings-label': 'Passkey (Biometric unlock)',
        'passkey-use-instead': 'Use Passkey instead',
        'passkey-confirm-pin': 'Enter PIN to verify identity before setting up Passkey',
        'passkey-enabled': '🔐 Passkey enabled — you can now unlock with biometrics',
        'passkey-disabled': 'Passkey disabled',
        'passkey-not-setup': 'Passkey not set up',
        'passkey-prf-unsupported': 'This browser does not support the PRF extension required for Passkey',
        'passkey-decrypt-failed': 'Passkey decryption failed — try PIN',
        'passkey-error': 'Passkey error: ',
        'passkey-unsupported': 'Passkey not supported on this device or browser',
        'passkey-status-enabled': '✅ Enabled — biometric unlock active',
        'passkey-status-disabled': '🔒 Disabled — PIN only',
        'passkey-disable-btn': 'Disable Passkey',
        'passkey-enable-btn': '🔐 Enable Passkey',
        'passkey-disable-confirm': 'Enter your PIN or use Passkey to disable passkey',
        'pin-need-upper': 'Must contain an uppercase letter (A–Z)',
        'pin-need-lower': 'Must contain a lowercase letter (a–z)',
        'pin-need-digit': 'Must contain a digit (0–9)',
        'pin-need-special': 'Must contain a special character (!@#$…)',
    }
}
