const walletLanguages = {
    'en': {
        'lang-alias': 'English',
        'open-regular': 'Regular wallet',
        'open-key': 'Open by key',
        'disclaimer': 'This page uses javascript to generate your addresses and sign your transactions within your browser, this means we never receive your private keys, this can be independently verified by reviewing the source code on Github.',
        'open-reminder': '<b>Notice:</b> Please make sure that you remember your account details, otherwise you may lose access to your funds.',
        'open': 'Open',
        'home': 'Home',
        'broadcast': 'Broadcast',
        'settings': 'Settings',
        'email-address': 'Email or other text (min 3 chars)',
        'password': 'Password',
        'password-confirm': 'Confirm password',
        'wif-key': 'WIF Private key',
        'show': 'Show',
        'hide': 'Hide',
        'address': 'Address',
        'public-key': 'Public Key',
        'private-key': 'Private Key',
        'broadcast-transaction': 'Broadcast transaction',
        'enter-transaction': 'Enter your signed transaction',
        'address-type': 'Address Type',
        'wallet-backend': 'Wallet Backend',
        'update': 'Update',
        'version': 'Version:',
        'wallet': 'Wallet',
        'close': 'Close',
        'send': 'Send',
        'history': 'History',
        'keys': 'Keys',
        'reset': 'Reset',
        'available-balance': 'Available balance:',
        'enter-address': 'Enter address',
        'amount': 'Amount',
        'fee': 'Fee',
        'recommended': 'recommended',
        'loading': 'Loading...',
        'send-sure': 'Are you sure?',
        'send-processing': 'Processing...',
        'success': 'Success',
        'failed': 'Failed',
        'send-it': 'Yes, send it!',
        'cancel': 'Cancel',
        'send-warning': 'You are one step away from sending',
        'send-warning-reverse': 'This action <strong>cannot</strong> be reversed. Are you sure about this?',
        'loading-utxo': 'Loading UTXOs...',
        'transaction-creation': 'Creating transaction...',
        'transaction-broadcasted': 'Transaction successfully broadcasted: ',
        'address-type-changed': 'Address type changed to',
        'backend-switched': 'Backend is switched to',
        'backend-down': 'don\'t seems to be available',
        'wallet-api': 'Wallet API backend',
        'open-wallet': 'Open Wallet',
        'bad-utxo': 'Unsupported UTXO type!',
        'balance-load-failed': 'We couldn\'t load wallet balance!',
        'not-enough-funds': 'You don\'t have enough funds for this transaction!',
        'not-valid-address': 'You must specify valid address!',
        'not-valid-amount': 'You must specify valid amount!',
        'not-valid-fee': 'You must specify valid fee!',
        'bad-priv-key': 'Bad WIF private key!',
        'not-enough-utxo': 'Not enough UTXO :(',
        'broadcast-failed': 'Transaction broadcast failed :(',
        'pass-not-match': 'Your passwords do not match!',
        'pass-too-short': 'Your password must be at least 10 chars long!',
        'small-fee': 'You should specify fee not less than',
        'scan-qr': 'Scan',
        'scan-modal-title': 'QR Code scanner',
        'webcam-message': 'Please make sure you have a webcam enabled',
        'webcam-loading': 'Loading camera...',
        'outputs-added': 'added to outputs',
        'pin-login-title': 'Saved wallet found',
        'pin-login-placeholder': 'Enter PIN to open',
        'pin-login-btn': 'Open',
        'pin-login-error': 'Wrong PIN, try again.',
        'pin-login-forget': 'Forget saved wallet',
        'settings-forget-wallet': 'Forget saved wallet',
        'pin-title-default': 'Wallet PIN',
        'pin-input-placeholder': 'PIN (min 8 chars)',
        'pin-create-title': 'Create wallet PIN',
        'pin-create-desc': 'Choose a strong PIN (min 8 characters, with at least one uppercase, lowercase, digit and special character). You will use it every time you open the wallet.',
        'pin-confirm-title': 'Confirm PIN',
        'pin-confirm-desc': 'Re-enter your PIN to confirm.',
        'pin-too-short': 'PIN must be at least 8 characters',
        'pin-mismatch': 'PINs do not match. Try again.',
        'ok': 'OK',
        'coin-control': 'Coin Control',
        'coin-control-manual': 'Manual UTXO selection',
        'coin-control-select-all': 'Select all mature',
        'coin-control-deselect-all': 'Deselect all',
        'coin-control-confs': 'Confs',
        'coin-control-type': 'Type',
        'coin-control-status': 'Status',
        'coin-control-no-utxo': 'No UTXOs',
        'coin-control-mature': 'mature',
        'coin-control-coinbase': 'coinbase',
        'coin-control-regular': 'regular',
        'coin-control-matures-in': 'Matures in',
        'coin-control-blocks': 'blocks',
        'coin-control-immature-title': 'Immature coinbase — cannot spend',
        'coin-control-selected': 'selected',
        'immature-mining': 'Immature (mining):',
        'immature-cannot-spend': 'cannot spend yet',
        'unconfirmed-balance': 'Unconfirmed:',
        'unconfirmed-mempool': 'pending in mempool',
        'history-loading': 'Loading history…',
        'no-transactions': 'No transactions yet',
        'history-failed': 'Failed to load history',
        'history-network-error': 'Network error',
        'history-view-all': 'View all',
        'history-on-explorer': 'transactions on explorer',
        'history-conf': 'conf',
        'history-confirmed': 'confirmed',
        'history-pending': 'pending',
        'copy-address': 'Copy address',
        'wallet-saved': 'Wallet saved. Next time just enter your PIN.',
        'wallet-deleted': 'Saved wallet deleted.',
        'identity-too-short': 'Identity must be at least 3 characters.',
        'auto-locked': 'Wallet locked due to inactivity.',
        'theme-light': '☀️ Light',
        'theme-dark': '🌙 Dark',
        'theme-auto': '🔄 Auto',
        'redeem-script': 'Redeem Script (SegWit)',
        'open-seed': '🌱 Seed Phrase',
        'seed-btn-create': '✨ Create New Wallet',
        'seed-btn-restore': '🔑 Restore from Seed Phrase',
        'seed-step1-label': 'Step 1 of 2 — Your Seed Phrase',
        'seed-write-warning': '⚠️ Write these words down in order and store them safely. Anyone with these words controls your funds.',
        'seed-print': 'Save PNG',
        'seed-next': 'Next →',
        'seed-step2-label': 'Step 2 of 2 — Verify Seed Phrase',
        'seed-verify-desc': 'Enter the words at these positions to confirm you saved them correctly:',
        'seed-verify-error-msg': 'Incorrect words. Please check your phrase.',
        'seed-confirm-pin': 'Confirm &amp; Set PIN',
        'seed-restore-title': 'Restore from Seed Phrase',
        'seed-word-count': 'Word count:',
        'seed-restore-placeholder': 'Enter your seed phrase words separated by spaces…',
        'seed-advanced': 'Advanced ▼',
        'seed-deriv-path': 'Derivation path',
        'seed-deriv-hint': 'Default: BIP84 native SegWit. Change for Electrum/Ledger compatibility.',
        'seed-restore-btn': 'Restore &amp; Set PIN',
        'seed-backup-label': 'Seed Phrase Backup',
        'seed-show-btn': '🌱 Show Seed Phrase (requires PIN or Passkey)',
        'seed-hide-btn': '🔒 Hide',
        'seed-word-num': 'Word',
        'seed-pin-modal-title': 'Enter PIN to view seed phrase',
        'seed-pin-modal-desc': 'Your seed phrase will be shown briefly.',
        'seed-pin-cancel':  'Due to cancellation, the seed has been regenerated for security.',
        'privkey-pin-desc': 'Enter PIN to reveal private key',
        'seed-count-mismatch': 'Expected {n} words, got {m}.',
        'seed-invalid-phrase': 'Invalid seed phrase. Check spelling and word order.',
        'seed-deriv-error': 'Derivation error:',
        'legacy-warn-password': '⚠️ <strong>Not recommended.</strong> This method derives a key from a password hash and is kept for backward compatibility only. Please migrate your funds to a Seed Phrase wallet.',
        'legacy-warn-key': '⚠️ <strong>Not recommended.</strong> Raw private key import is provided for compatibility only. Use a Seed Phrase wallet for better security and recoverability.',
        'seed-print-secret': 'Your Seed Phrase — Keep Secret!',
        'seed-print-warning': '⚠ Never share this image. Store it offline only.',
        'seed-path-label': 'Path:',
        'passkey-login-btn': 'Unlock with Passkey',
        'passkey-settings-label': 'Passkey (Biometric unlock)',
        'passkey-use-instead': 'Use Passkey instead',
        'passkey-confirm-pin': 'Enter PIN to verify identity before setting up Passkey',
        'passkey-enabled': '🔐 Passkey enabled — you can now unlock with biometrics',
        'passkey-disabled': 'Passkey disabled',
        'passkey-not-setup': 'Passkey not set up',
        'passkey-prf-unsupported': 'This browser does not support the PRF extension required for Passkey',
        'passkey-decrypt-failed': 'Passkey decryption failed — try PIN',
        'passkey-error': 'Passkey error: ',
        'passkey-unsupported': 'Passkey not supported on this device or browser',
        'passkey-status-enabled': '✅ Enabled — biometric unlock active',
        'passkey-status-disabled': '🔒 Disabled — PIN only',
        'passkey-disable-btn': 'Disable Passkey',
        'passkey-enable-btn': '🔐 Enable Passkey',
        'passkey-disable-confirm': 'Enter your PIN or use Passkey to disable passkey',
        'pin-need-upper': 'Must contain an uppercase letter (A–Z)',
        'pin-need-lower': 'Must contain a lowercase letter (a–z)',
        'pin-need-digit': 'Must contain a digit (0–9)',
        'pin-need-special': 'Must contain a special character (!@#$…)',
        'bip39-not-loaded': 'BIP39 library not loaded. Please reload the page.',
        'seed-crypto-error': 'Cryptographic error',
        'coin-control-unconfirmed-title': 'Cannot spend unconfirmed output',
    },
    'uk': {
        'lang-alias': 'Українська',
        'open-regular': 'Звичайний гаманець',
        'open-key': 'Відкрити ключем',
        'disclaimer': 'Ця сторінка використовує javascript для генерації ваших адрес та підпису транзакцій всередині браузера, це означає, що ми ніколи не отримуємо ваші приватні ключі, це можна перевірити незалежно, переглянувши вихідний код на Github.',
        'open-reminder': '<b>Увага:</b> Будь ласка переконайтесь, що ви запам\'ятали дані вашого акаунту, інакше ви можете втратити доступ до ваших коштів.',
        'open': 'Відкрити',
        'home': 'Домівка',
        'broadcast': 'Транслювати',
        'settings': 'Налаштування',
        'email-address': 'Електронна пошта',
        'password': 'Пароль',
        'password-confirm': 'Підтвердіть пароль',
        'wif-key': 'Приватний ключ WIF',
        'show': 'Показати',
        'hide': 'Сховати',
        'address': 'Адреса',
        'public-key': 'Публічний ключ',
        'private-key': 'Приватний ключ',
        'broadcast-transaction': 'Транслювати транзакцію',
        'enter-transaction': 'Введіть вашу підписану транзакцію',
        'address-type': 'Тип адреси',
        'wallet-backend': 'Бекенд гаманця',
        'update': 'Оновити',
        'version': 'Версія:',
        'wallet': 'Гаманець',
        'close': 'Закрити',
        'send': 'Надіслати',
        'history': 'Історія',
        'keys': 'Ключі',
        'reset': 'Скинути',
        'available-balance': 'Доступний баланс:',
        'enter-address': 'Введіть адресу',
        'amount': 'Сума',
        'fee': 'Комісія',
        'recommended': 'рекомендовано',
        'loading': 'Завантаження...',
        'send-sure': 'Ви впевнені?',
        'send-processing': 'Обробка...',
        'success': 'Успіх',
        'failed': 'Невдача',
        'send-it': 'Так, надіслати!',
        'cancel': 'Скасувати',
        'send-warning': 'Ви в одному кроці від того, щоб надіслати',
        'send-warning-reverse': 'Ця дія <strong>не може</strong> бути скасованою. Ви впевнені?',
        'loading-utxo': 'Завантаження UTXOs...',
        'transaction-creation': 'Створення транзакції...',
        'transaction-broadcasted': 'Транзакція успішно надіслана: ',
        'address-type-changed': 'Тип адрес змінений на',
        'backend-switched': 'Бекенд змінений на',
        'backend-down': 'виглядає мертвим',
        'wallet-api': 'API бекенду гаманця',
        'open-wallet': 'Відкрити Гаманець',
        'bad-utxo': 'Непідтримуваний тип UTXO!',
        'balance-load-failed': 'Нам не вдалося завантажити баланс вашого гаманця!',
        'not-enough-funds': 'У вас недостатньо коштів для цієї транзакції!',
        'not-valid-address': 'Ви маєте ввести дійсну адресу!',
        'not-valid-amount': 'Ви маєте ввести дійсну суму!',
        'not-valid-fee': 'Ви маєте ввести дійсну комісію!',
        'bad-priv-key': 'Недійсний WIF-приватний ключ!',
        'not-enough-utxo': 'Недостатньо UTXO :(',
        'broadcast-failed': 'Не вдалося транслювати транзакцію :(',
        'pass-not-match': 'Паролі не збігаються!',
        'pass-too-short': 'Ваш пароль повинен бути не менше 10 символів!',
        'small-fee': 'Ви маєте задати комісію не менше ніж',
        'scan-qr': 'Сканувати',
        'scan-modal-title': 'Зчитувач QR коду',
        'webcam-message': 'Будь ласка, переконайтеся, що у вас увімкнена веб-камера',
        'webcam-loading': 'Завантаження камери...',
        'outputs-added': 'додано до виходів',
        'pin-login-title': 'Знайдено збережений гаманець',
        'pin-login-placeholder': 'Введіть PIN для відкриття',
        'pin-login-btn': 'Відкрити',
        'pin-login-error': 'Неправильний PIN, спробуйте ще раз.',
        'pin-login-forget': 'Забути збережений гаманець',
        'settings-forget-wallet': 'Забути збережений гаманець',
        'pin-title-default': 'PIN гаманця',
        'pin-input-placeholder': 'PIN (мін. 8 символів)',
        'pin-create-title': 'Створити PIN гаманця',
        'pin-create-desc': 'Придумайте надійний PIN (мінімум 8 символів: велика і мала літера, цифра та спеціальний символ). Він знадобиться кожного разу при відкритті гаманця.',
        'pin-confirm-title': 'Підтвердити PIN',
        'pin-confirm-desc': 'Введіть PIN ще раз для підтвердження.',
        'pin-too-short': 'PIN має містити щонайменше 8 символів',
        'pin-mismatch': 'PIN-коди не збігаються. Спробуйте ще раз.',
        'ok': 'ОК',
        'coin-control': 'Контроль монет',
        'coin-control-manual': 'Ручний вибір UTXO',
        'coin-control-select-all': 'Вибрати всі зрілі',
        'coin-control-deselect-all': 'Скасувати вибір',
        'coin-control-confs': 'Підтв.',
        'coin-control-type': 'Тип',
        'coin-control-status': 'Статус',
        'coin-control-no-utxo': 'Немає UTXO',
        'coin-control-mature': 'зрілий',
        'coin-control-coinbase': 'coinbase',
        'coin-control-regular': 'звичайний',
        'coin-control-matures-in': 'Дозріє за',
        'coin-control-blocks': 'блоків',
        'coin-control-immature-title': 'Незрілий coinbase — неможливо витратити',
        'coin-control-selected': 'обрано',
        'immature-mining': 'Незрілий (майнінг):',
        'immature-cannot-spend': 'ще не можна витратити',
        'unconfirmed-balance': 'Непідтверджено:',
        'unconfirmed-mempool': 'очікує в мемпулі',
        'history-loading': 'Завантаження історії…',
        'no-transactions': 'Транзакцій ще немає',
        'history-failed': 'Не вдалося завантажити історію',
        'history-network-error': 'Помилка мережі',
        'history-view-all': 'Переглянути всі',
        'history-on-explorer': 'транзакцій в огляднику',
        'history-conf': 'підтв.',
        'history-confirmed': 'підтверджено',
        'history-pending': 'очікується',
        'copy-address': 'Скопіювати адресу',
        'wallet-saved': 'Гаманець збережено. Наступного разу просто введіть PIN.',
        'wallet-deleted': 'Збережений гаманець видалено.',
        'identity-too-short': 'Ідентифікатор має містити щонайменше 3 символи.',
        'auto-locked': 'Гаманець заблоковано через неактивність.',
        'theme-light': '☀️ Світла',
        'theme-dark': '🌙 Темна',
        'theme-auto': '🔄 Авто',
        'redeem-script': 'Розблокувальний скрипт (SegWit)',
        'open-seed': '🌱 Seed-фраза',
        'seed-btn-create': '✨ Створити новий гаманець',
        'seed-btn-restore': '🔑 Відновити з seed-фрази',
        'seed-step1-label': 'Крок 1 з 2 — Ваша seed-фраза',
        'seed-write-warning': '⚠️ Запишіть ці слова по порядку і зберігайте у безпеці. Будь-хто, хто знає ці слова, має доступ до ваших коштів.',
        'seed-print': 'Зберегти PNG',
        'seed-next': 'Далі →',
        'seed-step2-label': 'Крок 2 з 2 — Перевірка seed-фрази',
        'seed-verify-desc': 'Введіть слова на зазначених позиціях, щоб підтвердити, що ви їх записали:',
        'seed-verify-error-msg': 'Невірні слова. Перевірте вашу фразу.',
        'seed-confirm-pin': 'Підтвердити та встановити PIN',
        'seed-restore-title': 'Відновлення з seed-фрази',
        'seed-word-count': 'Кількість слів:',
        'seed-restore-placeholder': 'Введіть слова seed-фрази через пробіл…',
        'seed-advanced': 'Додатково ▼',
        'seed-deriv-path': 'Шлях деривації',
        'seed-deriv-hint': 'За замовчуванням: BIP84 native SegWit. Змініть для сумісності з Electrum/Ledger.',
        'seed-restore-btn': 'Відновити та встановити PIN',
        'seed-backup-label': 'Резервна копія seed-фрази',
        'seed-show-btn': '🌱 Показати seed-фразу (потрібен PIN або Passkey)',
        'seed-hide-btn': '🔒 Сховати',
        'seed-word-num': 'Слово',
        'seed-pin-modal-title': 'Введіть PIN для перегляду seed-фрази',
        'seed-pin-modal-desc': 'Ваша seed-фраза буде показана на короткий час.',
        'seed-pin-cancel':  'Через скасування seed-фразу було перегенеровано з міркувань безпеки.',
        'privkey-pin-desc': 'Введіть PIN для відображення приватного ключа',
        'seed-count-mismatch': 'Очікується {n} слів, отримано {m}.',
        'seed-invalid-phrase': 'Невірна seed-фраза. Перевірте орфографію та порядок слів.',
        'seed-deriv-error': 'Помилка деривації:',
        'legacy-warn-password': '⚠️ <strong>Не рекомендовано.</strong> Цей метод виводить ключ із хешу пароля та підтримується лише для зворотної сумісності. Перенесіть кошти на гаманець з Seed Phrase.',
        'legacy-warn-key': '⚠️ <strong>Не рекомендовано.</strong> Імпорт необробленого приватного ключа надається лише для сумісності. Використовуйте гаманець Seed Phrase для кращої безпеки та відновлення.',
        'seed-print-secret': 'Ваша seed-фраза — тримайте в таємниці!',
        'seed-print-warning': '⚠ Ніколи не передавайте це зображення. Зберігайте його лише офлайн.',
        'seed-path-label': 'Шлях:',
        'passkey-login-btn': 'Відкрити за допомогою Passkey',
        'passkey-settings-label': 'Passkey (Біометричне розблокування)',
        'passkey-use-instead': 'Використати Passkey',
        'passkey-confirm-pin': 'Введіть PIN для підтвердження особи перед налаштуванням Passkey',
        'passkey-enabled': '🔐 Passkey активовано — тепер можна розблоковувати біометрією',
        'passkey-disabled': 'Passkey вимкнено',
        'passkey-not-setup': 'Passkey не налаштовано',
        'passkey-prf-unsupported': 'Цей браузер не підтримує розширення PRF, потрібне для Passkey',
        'passkey-decrypt-failed': 'Розшифрування через Passkey не вдалось — спробуйте PIN',
        'passkey-error': 'Помилка Passkey: ',
        'passkey-unsupported': 'Passkey не підтримується на цьому пристрої або браузері',
        'passkey-status-enabled': '✅ Увімкнено — біометричне розблокування активне',
        'passkey-status-disabled': '🔒 Вимкнено — тільки PIN',
        'passkey-disable-btn': 'Вимкнути Passkey',
        'passkey-enable-btn': '🔐 Увімкнути Passkey',
        'passkey-disable-confirm': 'Введіть PIN або використайте Passkey для вимкнення',
        'pin-need-upper': 'Потрібна велика літера (A–Z)',
        'pin-need-lower': 'Потрібна мала літера (a–z)',
        'pin-need-digit': 'Потрібна цифра (0–9)',
        'pin-need-special': 'Потрібен спеціальний символ (!@#$…)',
        'bip39-not-loaded': 'Бібліотека BIP39 не завантажена. Будь ласка, перезавантажте сторінку.',
        'seed-crypto-error': 'Криптографічна помилка',
        'coin-control-unconfirmed-title': 'Неможливо витратити непідтверджений вихід',
    },
    'id': {
        'lang-alias': 'Indonesian',
        'open-regular': 'Buka dompet',
        'open-key': 'Buka dengan kunci',
        'disclaimer': 'Halaman ini menggunakan javascript untuk menghasilkan alamat dompet dan menandatangani transaksi Anda, ini berarti kami tidak pernah menerima kunci dompet pribadi Anda, ini diverifikasi secara terpisah dengan melihat sumber code di Github.',
        'open-reminder': '<b>Perhatikan:</b> Pastikan Anda mencadangkan detail dompet anda, jika tidak, Anda dapat kehilangan akses ke dana Anda.',
        'open': 'Buka',
        'home': 'Halaman depan',
        'broadcast': 'Siaran',
        'settings': 'Pengaturan',
        'email-address': 'Alamat Email',
        'password': 'Kata sandi',
        'password-confirm': 'Konfirmasi Kata sandi',
        'wif-key': 'Kunci pribadi WIF',
        'show': 'Tunjukkan',
        'hide': 'Sembunyikan',
        'address': 'Alamat',
        'public-key': 'Kunci Publik',
        'private-key': 'Kunci Pribadi',
        'broadcast-transaction': 'Siaran transaksi',
        'enter-transaction': 'Masukkan transaksi',
        'address-type': 'Tipe Alamat',
        'wallet-backend': 'Backend Dompet',
        'update': 'Perbarui',
        'version': 'Versi:',
        'wallet': 'Dompet',
        'close': 'Tutup',
        'send': 'Kirim',
        'history': 'Riwayat',
        'keys': 'Kunci',
        'reset': 'Mulai ulang',
        'available-balance': 'Saldo tersedia:',
        'enter-address': 'Masukan Alamat',
        'amount': 'Jumlah',
        'fee': 'Biaya',
        'recommended': 'Rekomendasi',
        'loading': 'Memuat...',
        'send-sure': 'Apakah kamu yakin?',
        'send-processing': 'Memproses...',
        'success': 'Sukses',
        'failed': 'Gagal',
        'send-it': 'Ya, Kirim sekarang!',
        'cancel': 'Batalkan',
        'send-warning': 'Tinggal selangkah lagi',
        'send-warning-reverse': 'Aksi ini <strong>tidak dapat</strong> dibatalkan. Apakah kamu yakin?',
        'loading-utxo': 'Memuat UTXOs...',
        'transaction-creation': 'Membuat Transaksi...',
        'transaction-broadcasted': 'Transaksi berhasil dikirim: ',
        'address-type-changed': 'Ganti tipe alamat',
        'backend-switched': 'Backend berpindah ke',
        'backend-down': 'Backend sepertinya tidak ada',
        'wallet-api': 'Dompet API',
        'open-wallet': 'Buka Dompet',
        'bad-utxo': 'Tidak mendukung tipe UTXO!',
        'balance-load-failed': 'Kami tidak bisa menampilkan jumlah saldo!',
        'not-enough-funds': 'Kamu tidak punya cukup saldo untuk transaksi ini!',
        'not-valid-address': 'Anda harus memasukkan alamat yang valid!',
        'not-valid-amount': 'Anda harus memasukkan jumlah yang valid!',
        'not-valid-fee': 'Anda harus memasukkan biaya yang valid!',
        'bad-priv-key': 'Kunci pribadi salah!',
        'not-enough-utxo': 'Tidak Cukup UTXO :(',
        'broadcast-failed': 'Siaran transaksi gagal :(',
        'pass-not-match': 'Password anda tidak cocok!',
        'pass-too-short': 'Kata sandi Anda setidaknya harus sepanjang 10 karakter!',
        'small-fee': 'Biaya terlalu kecil',
        'scan-qr': 'Pindai',
        'scan-modal-title': 'Pemindai QR',
        'webcam-message': 'Pastikan webcam Anda aktif',
        'webcam-loading': 'Memuat kamera...',
        'outputs-added': 'ditambahkan ke output',
        'pin-login-title': 'Dompet tersimpan ditemukan',
        'pin-login-placeholder': 'Masukkan PIN untuk membuka',
        'pin-login-btn': 'Buka',
        'pin-login-error': 'PIN salah, coba lagi.',
        'pin-login-forget': 'Lupakan dompet tersimpan',
        'settings-forget-wallet': 'Lupakan dompet tersimpan',
        'pin-title-default': 'PIN Dompet',
        'pin-input-placeholder': 'PIN (min 8 karakter)',
        'pin-create-title': 'Buat PIN dompet',
        'pin-create-desc': 'Pilih PIN yang kuat (min 8 karakter: huruf besar, kecil, angka, dan karakter khusus). Anda akan membutuhkannya setiap kali membuka dompet.',
        'pin-confirm-title': 'Konfirmasi PIN',
        'pin-confirm-desc': 'Masukkan ulang PIN Anda untuk konfirmasi.',
        'pin-too-short': 'PIN harus minimal 8 karakter',
        'pin-mismatch': 'PIN tidak cocok. Coba lagi.',
        'ok': 'OK',
        'coin-control': 'Kontrol Koin',
        'coin-control-manual': 'Pilihan UTXO manual',
        'coin-control-select-all': 'Pilih semua yang matang',
        'coin-control-deselect-all': 'Batalkan pilihan',
        'coin-control-confs': 'Konf.',
        'coin-control-type': 'Tipe',
        'coin-control-status': 'Status',
        'coin-control-no-utxo': 'Tidak ada UTXO',
        'coin-control-mature': 'matang',
        'coin-control-coinbase': 'coinbase',
        'coin-control-regular': 'reguler',
        'coin-control-matures-in': 'Matang dalam',
        'coin-control-blocks': 'blok',
        'coin-control-immature-title': 'Coinbase belum matang — tidak dapat digunakan',
        'coin-control-selected': 'dipilih',
        'immature-mining': 'Belum matang (mining):',
        'immature-cannot-spend': 'belum bisa digunakan',
        'unconfirmed-balance': 'Belum dikonfirmasi:',
        'unconfirmed-mempool': 'menunggu di mempool',
        'history-loading': 'Memuat riwayat…',
        'no-transactions': 'Belum ada transaksi',
        'history-failed': 'Gagal memuat riwayat',
        'history-network-error': 'Kesalahan jaringan',
        'history-view-all': 'Lihat semua',
        'history-on-explorer': 'transaksi di explorer',
        'history-conf': 'konf.',
        'history-confirmed': 'dikonfirmasi',
        'history-pending': 'tertunda',
        'copy-address': 'Salin alamat',
        'wallet-saved': 'Dompet disimpan. Lain kali cukup masukkan PIN Anda.',
        'wallet-deleted': 'Dompet tersimpan dihapus.',
        'identity-too-short': 'Identitas harus minimal 3 karakter.',
        'auto-locked': 'Dompet terkunci karena tidak aktif.',
        'theme-light': '☀️ Terang',
        'theme-dark': '🌙 Gelap',
        'theme-auto': '🔄 Otomatis',
        'redeem-script': 'Redeem Script (SegWit)',
        'open-seed': '🌱 Seed Phrase',
        'seed-btn-create': '✨ Buat Dompet Baru',
        'seed-btn-restore': '🔑 Pulihkan dari Seed Phrase',
        'seed-step1-label': 'Langkah 1 dari 2 — Seed Phrase Anda',
        'seed-write-warning': '⚠️ Catat kata-kata ini secara berurutan dan simpan dengan aman. Siapa pun yang memiliki kata-kata ini mengontrol dana Anda.',
        'seed-print': 'Simpan PNG',
        'seed-next': 'Berikutnya →',
        'seed-step2-label': 'Langkah 2 dari 2 — Verifikasi Seed Phrase',
        'seed-verify-desc': 'Masukkan kata-kata pada posisi ini untuk mengonfirmasi bahwa Anda telah menyimpannya:',
        'seed-verify-error-msg': 'Kata salah. Periksa kembali frasa Anda.',
        'seed-confirm-pin': 'Konfirmasi & Atur PIN',
        'seed-restore-title': 'Pulihkan dari Seed Phrase',
        'seed-word-count': 'Jumlah kata:',
        'seed-restore-placeholder': 'Masukkan kata-kata seed phrase dipisahkan spasi…',
        'seed-advanced': 'Lanjutan ▼',
        'seed-deriv-path': 'Jalur derivasi',
        'seed-deriv-hint': 'Default: BIP84 native SegWit. Ubah untuk kompatibilitas Electrum/Ledger.',
        'seed-restore-btn': 'Pulihkan & Atur PIN',
        'seed-backup-label': 'Cadangan Seed Phrase',
        'seed-show-btn': '🌱 Tampilkan Seed Phrase (perlu PIN atau Passkey)',
        'seed-hide-btn': '🔒 Sembunyikan',
        'seed-word-num': 'Kata',
        'seed-pin-modal-title': 'Masukkan PIN untuk melihat seed phrase',
        'seed-pin-modal-desc': 'Seed phrase Anda akan ditampilkan sebentar.',
        'seed-pin-cancel':  'Karena pembatalan, seed telah diregenerasi demi keamanan.',
        'privkey-pin-desc': 'Masukkan PIN untuk menampilkan kunci privat',
        'seed-count-mismatch': 'Diharapkan {n} kata, didapat {m}.',
        'seed-invalid-phrase': 'Seed phrase tidak valid. Periksa ejaan dan urutan kata.',
        'seed-deriv-error': 'Kesalahan derivasi:',
        'legacy-warn-password': '⚠️ <strong>Tidak disarankan.</strong> Metode ini menurunkan kunci dari hash kata sandi dan disimpan hanya untuk kompatibilitas mundur. Harap migrasikan dana Anda ke dompet Seed Phrase.',
        'legacy-warn-key': '⚠️ <strong>Tidak disarankan.</strong> Impor kunci privat mentah disediakan hanya untuk kompatibilitas. Gunakan dompet Seed Phrase untuk keamanan dan pemulihan yang lebih baik.',
        'seed-print-secret': 'Frasa Benih Anda — Jaga Kerahasiaannya!',
        'seed-print-warning': '⚠ Jangan pernah bagikan gambar ini. Simpan hanya secara offline.',
        'seed-path-label': 'Jalur:',
        'passkey-login-btn': 'Buka dengan Passkey',
        'passkey-settings-label': 'Passkey (Buka kunci biometrik)',
        'passkey-use-instead': 'Gunakan Passkey',
        'passkey-confirm-pin': 'Masukkan PIN untuk memverifikasi identitas sebelum menyiapkan Passkey',
        'passkey-enabled': '🔐 Passkey diaktifkan — kini Anda dapat membuka kunci dengan biometrik',
        'passkey-disabled': 'Passkey dinonaktifkan',
        'passkey-not-setup': 'Passkey belum dikonfigurasi',
        'passkey-prf-unsupported': 'Browser ini tidak mendukung ekstensi PRF yang diperlukan untuk Passkey',
        'passkey-decrypt-failed': 'Dekripsi Passkey gagal — coba gunakan PIN',
        'passkey-error': 'Error Passkey: ',
        'passkey-unsupported': 'Passkey tidak didukung di perangkat atau browser ini',
        'passkey-status-enabled': '✅ Aktif — buka kunci biometrik tersedia',
        'passkey-status-disabled': '🔒 Nonaktif — hanya PIN',
        'passkey-disable-btn': 'Nonaktifkan Passkey',
        'passkey-enable-btn': '🔐 Aktifkan Passkey',
        'passkey-disable-confirm': 'Masukkan PIN atau gunakan Passkey untuk menonaktifkannya',
        'pin-need-upper': 'Harus mengandung huruf besar (A–Z)',
        'pin-need-lower': 'Harus mengandung huruf kecil (a–z)',
        'pin-need-digit': 'Harus mengandung angka (0–9)',
        'pin-need-special': 'Harus mengandung karakter khusus (!@#$…)',
        'bip39-not-loaded': 'Perpustakaan BIP39 tidak termuat. Silakan muat ulang halaman.',
        'seed-crypto-error': 'Kesalahan kriptografi',
        'coin-control-unconfirmed-title': 'Tidak dapat menggunakan output yang belum dikonfirmasi',
    },
    'ja': {
        'lang-alias': '日本語',
        'open-regular': '通常ウォレット',
        'open-key': 'キーで開く',
        'disclaimer': 'このページではjavascriptを使用してアドレスを生成し、ブラウザ内で取引に署名します。そのため、秘密鍵を送信することはありません。これはGithubのソースコードで確認できます。',
        'open-reminder': '<b>お知らせ:</b> アカウント詳細を忘れないようにしてください。資金にアクセスできなくなる可能性があります。',
        'open': '開く',
        'home': 'ホーム',
        'broadcast': 'ブロードキャスト',
        'settings': '設定',
        'email-address': 'メールアドレス',
        'password': 'パスワード',
        'password-confirm': 'パスワード確認',
        'wif-key': 'WIF形式の秘密鍵',
        'show': '見る',
        'hide': '隠す',
        'address': 'アドレス',
        'public-key': '公開鍵 (パブリックキー)',
        'private-key': '秘密鍵 (プライベートキー)',
        'broadcast-transaction': '取引のブロードキャスト',
        'enter-transaction': '取引を入力してください',
        'address-type': 'アドレス形式',
        'wallet-backend': 'ウォレットバックエンド',
        'update': '更新',
        'version': 'バージョン:',
        'wallet': 'ウォレット',
        'close': '閉じる',
        'send': '送信',
        'history': '履歴',
        'keys': 'キー',
        'reset': 'リセット',
        'available-balance': '利用可能:',
        'enter-address': 'アドレスを入力してください',
        'amount': '金額',
        'fee': '手数料',
        'recommended': '推奨',
        'loading': '読み込み中...',
        'send-sure': '送信してよろしいですか？',
        'send-processing': '処理中...',
        'success': '成功',
        'failed': '失敗',
        'send-it': 'はい、送信します！',
        'cancel': 'キャンセル',
        'send-warning': '送信まであと少しです。',
        'send-warning-reverse': 'この操作は<strong>取消できません。</strong>本当によろしいですか？',
        'loading-utxo': 'UTXOsを読み込んでいます...',
        'transaction-creation': '取引を作成中...',
        'transaction-broadcasted': '取引のブロードキャストに成功しました: ',
        'address-type-changed': 'アドレス形式が次に変更されました',
        'backend-switched': 'バックエンドが次に変更されました',
        'backend-down': 'バックエンド使用不可能',
        'wallet-api': 'ウォレットAPIバックエンド',
        'open-wallet': 'ウォレットを開く',
        'bad-utxo': 'サポートされていないUTXOタイプです！',
        'balance-load-failed': 'ウォレット残高が読み込めませんでした！',
        'not-enough-funds': '取引に対して資金が不足しています',
        'not-valid-address': '正しいアドレスを指定してください！',
        'not-valid-amount': '正しい金額を指定してください！',
        'not-valid-fee': '正しい手数料を指定してください！',
        'bad-priv-key': '秘密鍵が間違っています',
        'not-enough-utxo': 'UTXOが不足しています :(',
        'broadcast-failed': '取引のブロードキャストに失敗しました :(',
        'pass-not-match': 'パスワードが間違っています！',
        'pass-too-short': 'パスワードは10文字以上必要です！',
        'small-fee': '最低手数料は',
        'scan-qr': 'スキャン',
        'scan-modal-title': 'QRコードリーダー',
        'webcam-message': 'ウェブカメラが有効か確認してください',
        'webcam-loading': 'カメラ読み込み中...',
        'outputs-added': '出力に追加',
        'pin-login-title': '保存されたウォレットが見つかりました',
        'pin-login-placeholder': 'PINを入力して開く',
        'pin-login-btn': '開く',
        'pin-login-error': 'PINが間違っています。再入力してください。',
        'pin-login-forget': '保存されたウォレットを忘れる',
        'settings-forget-wallet': '保存されたウォレットを忘れる',
        'pin-title-default': 'ウォレットPIN',
        'pin-input-placeholder': 'PIN（8文字以上）',
        'pin-create-title': 'ウォレットPINの作成',
        'pin-create-desc': 'PINを設定してください（最低8文字：大文字・小文字・数字・特殊文字を含む）。ウォレットを開くたびに使用します。',
        'pin-confirm-title': 'PINの確認',
        'pin-confirm-desc': '確認のためPINを再入力してください。',
        'pin-too-short': 'PINは8文字以上必要です',
        'pin-mismatch': 'PINが一致しません。もう一度試してください。',
        'ok': 'OK',
        'coin-control': 'コインコントロール',
        'coin-control-manual': 'UTXO手動選択',
        'coin-control-select-all': '成熟済みをすべて選択',
        'coin-control-deselect-all': '全選択解除',
        'coin-control-confs': '確認数',
        'coin-control-type': '種類',
        'coin-control-status': '状態',
        'coin-control-no-utxo': 'UTXOなし',
        'coin-control-mature': '使用可',
        'coin-control-coinbase': 'コインベース',
        'coin-control-regular': '通常',
        'coin-control-matures-in': '成熟まで',
        'coin-control-blocks': 'ブロック',
        'coin-control-immature-title': '未成熟なコインベース — 使用不可',
        'coin-control-selected': '選択済み',
        'immature-mining': '未成熟 (マイニング):',
        'immature-cannot-spend': 'まだ使用できません',
        'unconfirmed-balance': '未確認:',
        'unconfirmed-mempool': 'mempoolで保留中',
        'history-loading': '履歴を読み込み中…',
        'no-transactions': 'トランザクションはまだありません',
        'history-failed': '履歴の読み込みに失敗しました',
        'history-network-error': 'ネットワークエラー',
        'history-view-all': 'すべての',
        'history-on-explorer': 'トランザクションをエクスプローラーで表示',
        'history-conf': '確認',
        'history-confirmed': '確認済み',
        'history-pending': '保留中',
        'copy-address': 'アドレスをコピー',
        'wallet-saved': 'ウォレットを保存しました。次回はPINを入力するだけです。',
        'wallet-deleted': '保存されたウォレットを削除しました。',
        'identity-too-short': 'IDは3文字以上必要です。',
        'auto-locked': 'ウォレットが非アクティブのためロックされました。',
        'theme-light': '☀️ ライト',
        'theme-dark': '🌙 ダーク',
        'theme-auto': '🔄 自動',
        'redeem-script': 'リデームスクリプト (SegWit)',
        'open-seed': '🌱 シードフレーズ',
        'seed-btn-create': '✨ 新しいウォレットを作成',
        'seed-btn-restore': '🔑 シードフレーズから復元',
        'seed-step1-label': 'ステップ 1/2 — シードフレーズ',
        'seed-write-warning': '⚠️ これらの単語を順番に書き留め、安全に保管してください。これらの単語を知っている人は誰でもあなたの資金にアクセスできます。',
        'seed-print': 'PNG保存',
        'seed-next': '次へ →',
        'seed-step2-label': 'ステップ 2/2 — シードフレーズを確認',
        'seed-verify-desc': 'これらの位置の単語を入力して、正しく保存されたことを確認してください：',
        'seed-verify-error-msg': '単語が正しくありません。フレーズを確認してください。',
        'seed-confirm-pin': '確認してPINを設定',
        'seed-restore-title': 'シードフレーズから復元',
        'seed-word-count': '単語数：',
        'seed-restore-placeholder': 'シードフレーズの単語をスペースで区切って入力…',
        'seed-advanced': '詳細設定 ▼',
        'seed-deriv-path': '派生パス',
        'seed-deriv-hint': 'デフォルト：BIP84 native SegWit。Electrum/Ledgerとの互換性のために変更可能。',
        'seed-restore-btn': '復元してPINを設定',
        'seed-backup-label': 'シードフレーズのバックアップ',
        'seed-show-btn': '🌱 シードフレーズを表示（PIN またはパスキー必要）',
        'seed-hide-btn': '🔒 非表示',
        'seed-word-num': '単語',
        'seed-pin-modal-title': 'シードフレーズを表示するためにPINを入力',
        'seed-pin-modal-desc': 'シードフレーズが短時間表示されます。',
        'seed-pin-cancel':  'キャンセルのため、セキュリティ上の理由からシードが再生成されました。',
        'privkey-pin-desc': '秘密鍵を表示するためにPINを入力',
        'seed-count-mismatch': '{n}単語が期待されましたが、{m}単語が入力されました。',
        'seed-invalid-phrase': '無効なシードフレーズです。スペルと単語の順序を確認してください。',
        'seed-deriv-error': '派生エラー：',
        'legacy-warn-password': '⚠️ <strong>非推奨。</strong> この方式はパスワードハッシュから鍵を導出するもので、後方互換性のためにのみ保持されています。資金をシードフレーズウォレットに移行してください。',
        'legacy-warn-key': '⚠️ <strong>非推奨。</strong> 生の秘密鍵のインポートは互換性のためにのみ提供されています。より高いセキュリティと回復性のためにシードフレーズウォレットをご利用ください。',
        'seed-print-secret': 'シードフレーズ — 秘密にしてください！',
        'seed-print-warning': '⚠ この画像を決して共有しないでください。オフラインでのみ保管してください。',
        'seed-path-label': 'パス:',
        'passkey-login-btn': 'パスキーで開く',
        'passkey-settings-label': 'パスキー（生体認証で解除）',
        'passkey-use-instead': 'パスキーを使用する',
        'passkey-confirm-pin': 'パスキーを設定する前に、PINで本人確認をしてください',
        'passkey-enabled': '🔐 パスキーが有効になりました — 生体認証でロック解除できます',
        'passkey-disabled': 'パスキーが無効になりました',
        'passkey-not-setup': 'パスキーが設定されていません',
        'passkey-prf-unsupported': 'このブラウザはパスキーに必要なPRF拡張をサポートしていません',
        'passkey-decrypt-failed': 'パスキーによる復号に失敗しました — PINをお試しください',
        'passkey-error': 'パスキーエラー: ',
        'passkey-unsupported': 'このデバイスまたはブラウザではパスキーがサポートされていません',
        'passkey-status-enabled': '✅ 有効 — 生体認証解除がアクティブです',
        'passkey-status-disabled': '🔒 無効 — PINのみ',
        'passkey-disable-btn': 'パスキーを無効にする',
        'passkey-enable-btn': '🔐 パスキーを有効にする',
        'passkey-disable-confirm': 'パスキーを無効にするには、PINを入力するかパスキーを使用してください',
        'pin-need-upper': '大文字（A–Z）が必要です',
        'pin-need-lower': '小文字（a–z）が必要です',
        'pin-need-digit': '数字（0–9）が必要です',
        'pin-need-special': '特殊文字（!@#$…）が必要です',
        'bip39-not-loaded': 'BIP39ライブラリが読み込まれていません。ページを再読み込みしてください。',
        'seed-crypto-error': '暗号化エラー',
        'coin-control-unconfirmed-title': '未確認のアウトプットは使用できません',
    },
    'zh': {
        'lang-alias': '简体中文',
        'open-regular': '普通钱包',
        'open-key': '密钥钱包',
        'disclaimer': '此页面通过javascript脚本在浏览器中生成地址并为交易签名，这意味着我们不会并且无法保存您的私钥，您可通过我们公布在Github上的源码来验证相关内容的有效性.',
        'open-reminder': '<b>提醒:</b> 请务必记住您的帐户详细信息，否则您可能无法使用您的资金。',
        'open': '打开',
        'home': '首页',
        'broadcast': '广播',
        'settings': '设置',
        'email-address': '邮箱地址',
        'password': '密码',
        'password-confirm': '确认密码',
        'wif-key': 'WIF私钥',
        'show': '显示',
        'hide': '隐藏',
        'address': '地址',
        'public-key': '公钥',
        'private-key': '私钥',
        'broadcast-transaction': '广播交易',
        'enter-transaction': '输入交易签名',
        'address-type': '地址类型',
        'wallet-backend': '钱包接口',
        'update': '更新',
        'version': '版本:',
        'wallet': '钱包',
        'close': '关闭',
        'send': '发送',
        'history': '历史',
        'keys': '密钥',
        'reset': '重置',
        'available-balance': '可用余额:',
        'enter-address': '输入地址',
        'amount': '数量',
        'fee': '交易费用',
        'recommended': '推荐',
        'loading': '加载中...',
        'send-sure': '你确定吗?',
        'send-processing': '处理中...',
        'success': '成功',
        'failed': '失败',
        'send-it': '确定，发送!',
        'cancel': '取消',
        'send-warning': '离交易发送仅一步之遥',
        'send-warning-reverse': '此操作<strong>不可逆转</strong>，你确定吗?',
        'loading-utxo': '加载UTXO中...',
        'transaction-creation': '创建交易中...',
        'transaction-broadcasted': '交易已成功广播: ',
        'address-type-changed': '地址类型切换至',
        'backend-switched': '后端接口已切换至',
        'backend-down': '似乎不可用',
        'wallet-api': '钱包API接口',
        'open-wallet': '打开钱包',
        'bad-utxo': '不支持的UTXO类型!',
        'balance-load-failed': '钱包可用余额加载失败!',
        'not-enough-funds': '可用余额不足以支持本次交易!',
        'not-valid-address': '请使用有效的钱包地址!',
        'not-valid-amount': '请使用有效的数量!',
        'not-valid-fee': '请指定有效的手续费用金额!',
        'bad-priv-key': '错误的WIF私钥!',
        'not-enough-utxo': '没有足够的UTXO :(',
        'broadcast-failed': '交易广播失败 :(',
        'pass-not-match': '两次输入的密码不匹配!',
        'pass-too-short': '密码不能少于10个字符!',
        'small-fee': '手续费金额不能低于',
        'scan-qr': '扫描',
        'scan-modal-title': 'QR扫描器',
        'webcam-message': '请确保摄像头已启用',
        'webcam-loading': '摄像头加载中...',
        'outputs-added': '已添加到输出',
        'pin-login-title': '发现已保存的钱包',
        'pin-login-placeholder': '输入PIN以打开',
        'pin-login-btn': '打开',
        'pin-login-error': 'PIN错误，请重试。',
        'pin-login-forget': '忘记已保存的钱包',
        'settings-forget-wallet': '忘记已保存的钱包',
        'pin-title-default': '钱包PIN',
        'pin-input-placeholder': 'PIN（最少8位）',
        'pin-create-title': '创建钱包PIN',
        'pin-create-desc': '设置强PIN（至少8个字符：包含大写、小写、数字和特殊字符）。每次打开钱包时需要使用。',
        'pin-confirm-title': '确认PIN',
        'pin-confirm-desc': '请再次输入PIN以确认。',
        'pin-too-short': 'PIN至少需要8位字符',
        'pin-mismatch': 'PIN不匹配，请重试。',
        'ok': '确定',
        'coin-control': '币控',
        'coin-control-manual': '手动选择UTXO',
        'coin-control-select-all': '选择所有成熟的',
        'coin-control-deselect-all': '取消全选',
        'coin-control-confs': '确认',
        'coin-control-type': '类型',
        'coin-control-status': '状态',
        'coin-control-no-utxo': '没有UTXO',
        'coin-control-mature': '成熟',
        'coin-control-coinbase': '矿币',
        'coin-control-regular': '普通',
        'coin-control-matures-in': '成熟还需',
        'coin-control-blocks': '个区块',
        'coin-control-immature-title': '未成熟矿币 — 无法使用',
        'coin-control-selected': '已选',
        'immature-mining': '未成熟（挖矿）:',
        'immature-cannot-spend': '暂不可用',
        'unconfirmed-balance': '未确认:',
        'unconfirmed-mempool': '等待中（mempool）',
        'history-loading': '加载历史中…',
        'no-transactions': '暂无交易',
        'history-failed': '加载历史失败',
        'history-network-error': '网络错误',
        'history-view-all': '查看全部',
        'history-on-explorer': '笔交易（在浏览器中）',
        'history-conf': '确认',
        'history-confirmed': '已确认',
        'history-pending': '待处理',
        'copy-address': '复制地址',
        'wallet-saved': '钱包已保存。下次只需输入PIN即可。',
        'wallet-deleted': '已保存的钱包已删除。',
        'identity-too-short': '身份标识至少需要3个字符。',
        'auto-locked': '钱包因长时间未活动已锁定。',
        'theme-light': '☀️ 浅色',
        'theme-dark': '🌙 深色',
        'theme-auto': '🔄 自动',
        'redeem-script': '赎回脚本 (SegWit)',
        'open-seed': '🌱 助记词',
        'seed-btn-create': '✨ 创建新钱包',
        'seed-btn-restore': '🔑 从助记词恢复',
        'seed-step1-label': '第 1 步 / 共 2 步 — 您的助记词',
        'seed-write-warning': '⚠️ 请按顺序写下这些单词并妥善保存。任何拥有这些单词的人都可以控制您的资金。',
        'seed-print': '保存PNG',
        'seed-next': '下一步 →',
        'seed-step2-label': '第 2 步 / 共 2 步 — 验证助记词',
        'seed-verify-desc': '输入这些位置的单词以确认您已正确保存：',
        'seed-verify-error-msg': '单词错误，请检查您的助记词。',
        'seed-confirm-pin': '确认并设置PIN',
        'seed-restore-title': '从助记词恢复',
        'seed-word-count': '单词数量：',
        'seed-restore-placeholder': '用空格分隔输入助记词单词…',
        'seed-advanced': '高级设置 ▼',
        'seed-deriv-path': '派生路径',
        'seed-deriv-hint': '默认：BIP84 原生 SegWit。可更改以兼容 Electrum/Ledger。',
        'seed-restore-btn': '恢复并设置PIN',
        'seed-backup-label': '助记词备份',
        'seed-show-btn': '🌱 显示助记词（需要PIN或通证密钥）',
        'seed-hide-btn': '🔒 隐藏',
        'seed-word-num': '单词',
        'seed-pin-modal-title': '输入PIN以查看助记词',
        'seed-pin-modal-desc': '您的助记词将短暂显示。',
        'seed-pin-cancel':  '由于取消操作，出于安全原因助记词已重新生成。',
        'privkey-pin-desc': '输入PIN以显示私钥',
        'seed-count-mismatch': '预期 {n} 个词，实际输入了 {m} 个。',
        'seed-invalid-phrase': '助记词无效，请检查拼写和单词顺序。',
        'seed-deriv-error': '派生错误：',
        'legacy-warn-password': '⚠️ <strong>不推荐。</strong> 此方法从密码哈希派生密钥，仅为向后兼容而保留。请将您的资金迁移到助记词钱包。',
        'legacy-warn-key': '⚠️ <strong>不推荐。</strong> 提供原始私钥导入仅为了兼容性。请使用助记词钱包以获得更好的安全性和可恢复性。',
        'seed-print-secret': '您的助记词 — 请保密！',
        'seed-print-warning': '⚠ 请勿分享此图像。仅离线存储。',
        'seed-path-label': '路径：',
        'passkey-login-btn': '通证解锁',
        'passkey-settings-label': '通证密钥（生物识别解锁）',
        'passkey-use-instead': '使用通证密钥',
        'passkey-confirm-pin': '设置通证密钥前，请先输入PIN以验证身份',
        'passkey-enabled': '🔐 通证密钥已启用 — 现在可用生物识别解锁',
        'passkey-disabled': '通证密钥已禁用',
        'passkey-not-setup': '通证密钥尚未配置',
        'passkey-prf-unsupported': '此浏览器不支持通证密钥所需的PRF扩展',
        'passkey-decrypt-failed': '通证密钥解密失败 — 请尝试PIN',
        'passkey-error': '通证密钥错误：',
        'passkey-unsupported': '此设备或浏览器不支持通证密钥',
        'passkey-status-enabled': '✅ 已启用 — 生物识别解锁已激活',
        'passkey-status-disabled': '🔒 已禁用 — 仅使用PIN',
        'passkey-disable-btn': '禁用通证密钥',
        'passkey-enable-btn': '🔐 启用通证密钥',
        'passkey-disable-confirm': '输入PIN或使用通证密钥来禁用通证密钥',
        'pin-need-upper': '须包含大写字母（A–Z）',
        'pin-need-lower': '须包含小写字母（a–z）',
        'pin-need-digit': '须包含数字（0–9）',
        'pin-need-special': '须包含特殊字符（!@#$…）',
        'bip39-not-loaded': 'BIP39 库未加载，请重新加载页面。',
        'seed-crypto-error': '加密错误',
        'coin-control-unconfirmed-title': '无法使用未确认的输出',
    },
    'es': {
        'lang-alias': 'Español',
        'open-regular': 'Cartera regular',
        'open-key': 'Abrir con llave',
        'disclaimer': 'Esta página utiliza Javascript para generar sus direcciones y firmar sus transacciones en su navegador, Esto implica que nunca recibimos sus claves privada, Esto puede ser verificado independientemente por medio de la revisión el código de fuente en Github.',
        'open-reminder': '<b>Aviso:</b> Por favor asegúrese que se acuerda sus detalles de cuenta, podría perder el acceso de los fondos',
        'open': 'Abrir',
        'home': 'Página Inicial',
        'broadcast': 'Transmitir',
        'settings': 'Configuraciones',
        'email-address': 'Correo electrónico',
        'password': 'Contraseña',
        'password-confirm': 'Confirma la contraseña',
        'wif-key': 'WIF Clave privada',
        'show': 'Mostrar',
        'hide': 'Esconder',
        'address': 'Dirección',
        'public-key': 'Clave pública',
        'private-key': 'Clave privada',
        'broadcast-transaction': 'Transmitir transacción',
        'enter-transaction': 'Introduzca sus transaccion firmado',
        'address-type': 'Tipo de dirección',
        'wallet-backend': 'Cartera Backend',
        'update': 'Actualización',
        'version': 'Versión:',
        'wallet': 'Cartera',
        'close': 'Cerrar',
        'send': 'Enviar',
        'history': 'historia',
        'keys': 'Llaves',
        'reset': 'Reiniciar',
        'available-balance': 'Saldo disponible:',
        'enter-address': 'Introduce dirección',
        'amount': 'Cantidad',
        'fee': 'Cuota',
        'recommended': 'recomendado',
        'loading': 'Cargando...',
        'send-sure': '¿Estás seguro?',
        'send-processing': 'Procesamiento...',
        'success': 'éxito',
        'failed': 'falló',
        'send-it': 'sí, envíalo!',
        'cancel': 'Cancelo',
        'send-warning': 'Estás a un paso de envío',
        'send-warning-reverse': 'esta acción <strong>no puede</strong> ser revertida. ¿Estás seguro de esto?',
        'loading-utxo': 'Cargando UTXOs...',
        'transaction-creation': 'Creación de transacción...',
        'transaction-broadcasted': 'Transacción transmitida con éxito: ',
        'address-type-changed': 'Tipo de dirección cambiado a',
        'backend-switched': 'Backend se cambia a',
        'backend-down': 'no parece estar disponible',
        'wallet-api': 'Backend de cartera API',
        'open-wallet': 'Abrir cartera',
        'bad-utxo': 'Tipo UTXO no compatible',
        'balance-load-failed': '¡No pudimos cargar el saldo de la cartera!',
        'not-enough-funds': '¡No tienes suficientes fondos para esta transacción!',
        'not-valid-address': '¡Debe especificar una dirección válida!',
        'not-valid-amount': '¡Debe especificar la cantidad válida!',
        'not-valid-fee': 'Debe especificar válida cuota!',
        'bad-priv-key': 'Mala WIF clave privada!',
        'not-enough-utxo': 'No hay suficiente UTXO :(',
        'broadcast-failed': 'La transacción transmitió fallado :(',
        'pass-not-match': '¡Tus contraseñas no coinciden!',
        'pass-too-short': 'Su contraseña debe tener al menos 10 caracteres!',
        'small-fee': 'Debe especificar fee no menos de',
        'scan-qr': 'Escanear',
        'scan-modal-title': 'Escáner QR',
        'webcam-message': 'Asegúrese de tener una cámara web habilitada',
        'webcam-loading': 'Cargando cámara...',
        'outputs-added': 'agregado a salidas',
        'pin-login-title': 'Cartera guardada encontrada',
        'pin-login-placeholder': 'Ingrese PIN para abrir',
        'pin-login-btn': 'Abrir',
        'pin-login-error': 'PIN incorrecto, intente de nuevo.',
        'pin-login-forget': 'Olvidar cartera guardada',
        'settings-forget-wallet': 'Olvidar cartera guardada',
        'pin-title-default': 'PIN de cartera',
        'pin-input-placeholder': 'PIN (mín. 8 caracteres)',
        'pin-create-title': 'Crear PIN de cartera',
        'pin-create-desc': 'Elija un PIN seguro (mínimo 8 caracteres: mayúscula, minúscula, dígito y carácter especial). Lo necesitará cada vez que abra la cartera.',
        'pin-confirm-title': 'Confirmar PIN',
        'pin-confirm-desc': 'Vuelva a ingresar su PIN para confirmar.',
        'pin-too-short': 'El PIN debe tener al menos 8 caracteres',
        'pin-mismatch': 'Los PIN no coinciden. Inténtelo de nuevo.',
        'ok': 'Aceptar',
        'coin-control': 'Control de monedas',
        'coin-control-manual': 'Selección manual de UTXO',
        'coin-control-select-all': 'Seleccionar todos los maduros',
        'coin-control-deselect-all': 'Deseleccionar todo',
        'coin-control-confs': 'Confs.',
        'coin-control-type': 'Tipo',
        'coin-control-status': 'Estado',
        'coin-control-no-utxo': 'Sin UTXO',
        'coin-control-mature': 'maduro',
        'coin-control-coinbase': 'coinbase',
        'coin-control-regular': 'regular',
        'coin-control-matures-in': 'Madura en',
        'coin-control-blocks': 'bloques',
        'coin-control-immature-title': 'Coinbase inmaduro — no se puede gastar',
        'coin-control-selected': 'seleccionado',
        'immature-mining': 'Inmaduro (minería):',
        'immature-cannot-spend': 'aún no se puede gastar',
        'unconfirmed-balance': 'Sin confirmar:',
        'unconfirmed-mempool': 'pendiente en mempool',
        'history-loading': 'Cargando historial…',
        'no-transactions': 'Aún no hay transacciones',
        'history-failed': 'Error al cargar el historial',
        'history-network-error': 'Error de red',
        'history-view-all': 'Ver todas las',
        'history-on-explorer': 'transacciones en el explorador',
        'history-conf': 'conf.',
        'history-confirmed': 'confirmado',
        'history-pending': 'pendiente',
        'copy-address': 'Copiar dirección',
        'wallet-saved': 'Cartera guardada. La próxima vez solo ingresa tu PIN.',
        'wallet-deleted': 'Cartera guardada eliminada.',
        'identity-too-short': 'La identidad debe tener al menos 3 caracteres.',
        'auto-locked': 'Cartera bloqueada por inactividad.',
        'theme-light': '☀️ Claro',
        'theme-dark': '🌙 Oscuro',
        'theme-auto': '🔄 Auto',
        'redeem-script': 'Redeem Script (SegWit)',
        'open-seed': '🌱 Frase semilla',
        'seed-btn-create': '✨ Crear nueva cartera',
        'seed-btn-restore': '🔑 Restaurar desde frase semilla',
        'seed-step1-label': 'Paso 1 de 2 — Tu frase semilla',
        'seed-write-warning': '⚠️ Escribe estas palabras en orden y guárdalas de forma segura. Cualquiera con estas palabras controla tus fondos.',
        'seed-print': 'Guardar PNG',
        'seed-next': 'Siguiente →',
        'seed-step2-label': 'Paso 2 de 2 — Verificar frase semilla',
        'seed-verify-desc': 'Ingresa las palabras en estas posiciones para confirmar que las guardaste correctamente:',
        'seed-verify-error-msg': 'Palabras incorrectas. Revisa tu frase.',
        'seed-confirm-pin': 'Confirmar y establecer PIN',
        'seed-restore-title': 'Restaurar desde frase semilla',
        'seed-word-count': 'Número de palabras:',
        'seed-restore-placeholder': 'Ingresa las palabras de tu frase semilla separadas por espacios…',
        'seed-advanced': 'Avanzado ▼',
        'seed-deriv-path': 'Ruta de derivación',
        'seed-deriv-hint': 'Por defecto: BIP84 native SegWit. Cambia para compatibilidad con Electrum/Ledger.',
        'seed-restore-btn': 'Restaurar y establecer PIN',
        'seed-backup-label': 'Copia de seguridad de frase semilla',
        'seed-show-btn': '🌱 Mostrar frase semilla (requiere PIN o Passkey)',
        'seed-hide-btn': '🔒 Ocultar',
        'seed-word-num': 'Palabra',
        'seed-pin-modal-title': 'Ingresa PIN para ver la frase semilla',
        'seed-pin-modal-desc': 'Tu frase semilla se mostrará brevemente.',
        'seed-pin-cancel':  'Debido a la cancelación, la semilla fue regenerada por seguridad.',
        'privkey-pin-desc': 'Ingresa PIN para revelar la clave privada',
        'seed-count-mismatch': 'Se esperaban {n} palabras, se obtuvo {m}.',
        'seed-invalid-phrase': 'Frase semilla no válida. Verifica la ortografía y el orden de las palabras.',
        'seed-deriv-error': 'Error de derivación:',
        'legacy-warn-password': '⚠️ <strong>No recomendado.</strong> Este método deriva una clave de un hash de contraseña y se mantiene solo por compatibilidad con versiones anteriores. Por favor, migre sus fondos a una cartera con Frase Semilla.',
        'legacy-warn-key': '⚠️ <strong>No recomendado.</strong> La importación de clave privada sin procesar se proporciona solo por compatibilidad. Use una cartera de Frase Semilla para mayor seguridad y recuperabilidad.',
        'seed-print-secret': 'Su Frase Semilla — ¡Manténgala en Secreto!',
        'seed-print-warning': '⚠ Nunca comparta esta imagen. Almacénela solo sin conexión.',
        'seed-path-label': 'Ruta:',
        'passkey-login-btn': 'Abrir con Passkey',
        'passkey-settings-label': 'Passkey (Desbloqueo biométrico)',
        'passkey-use-instead': 'Usar Passkey',
        'passkey-confirm-pin': 'Ingresa tu PIN para verificar identidad antes de configurar la Passkey',
        'passkey-enabled': '🔐 Passkey activada — ahora puedes desbloquear con biometría',
        'passkey-disabled': 'Passkey desactivada',
        'passkey-not-setup': 'Passkey no configurada',
        'passkey-prf-unsupported': 'Este navegador no admite la extensión PRF necesaria para Passkey',
        'passkey-decrypt-failed': 'Descifrado con Passkey fallido — intenta con el PIN',
        'passkey-error': 'Error de Passkey: ',
        'passkey-unsupported': 'Passkey no compatible con este dispositivo o navegador',
        'passkey-status-enabled': '✅ Activada — desbloqueo biométrico activo',
        'passkey-status-disabled': '🔒 Desactivada — solo PIN',
        'passkey-disable-btn': 'Desactivar Passkey',
        'passkey-enable-btn': '🔐 Activar Passkey',
        'passkey-disable-confirm': 'Ingresa tu PIN o usa la Passkey para desactivarla',
        'pin-need-upper': 'Debe contener una letra mayúscula (A–Z)',
        'pin-need-lower': 'Debe contener una letra minúscula (a–z)',
        'pin-need-digit': 'Debe contener un dígito (0–9)',
        'pin-need-special': 'Debe contener un carácter especial (!@#$…)',
        'bip39-not-loaded': 'La biblioteca BIP39 no está cargada. Por favor, recarga la página.',
        'seed-crypto-error': 'Error criptográfico',
        'coin-control-unconfirmed-title': 'No se puede gastar una salida no confirmada',
    },
    'ru': {
        'lang-alias': 'Русский',
        'open-regular': 'Обычный кошелек',
        'open-key': 'Открыть ключом',
        'disclaimer': 'Эта страница использует javascript для генерации Вашего адреса и подписи Ваших транзакциий внутри браузера, это значит, что мы никогда не получаем Ваши приватные ключи, и это можно независимо проверить, прочитав исходный код на GitHub.',
        'open-reminder': '<b>Внимание:</b> Пожалуйста убедитесь, что Вы запомнили детали вашего аккаунта, иначе Вы можете потерять доступ к своим денежным средствам.',
        'open': 'Открыть',
        'home': 'Домой',
        'broadcast': 'Транслировать',
        'settings': 'Настройки',
        'email-address': 'Электронная почта',
        'password': 'Пароль',
        'password-confirm': 'Подтвердить пароль',
        'wif-key': 'Приватный ключ WIF',
        'show': 'Показать',
        'hide': 'Спрятать',
        'address': 'Адрес',
        'public-key': 'Публичный Ключ',
        'private-key': 'Приватный Ключ',
        'broadcast-transaction': 'Транслировать транзакцию',
        'enter-transaction': 'Введите Вашу подписанную транзакцию',
        'address-type': 'Тип Адреса',
        'wallet-backend': 'Бэкэнд Кошелька',
        'update': 'Обновить',
        'version': 'Версия:',
        'wallet': 'Кошелек',
        'close': 'Закрыть',
        'send': 'Отправить',
        'history': 'История',
        'keys': 'Ключи',
        'reset': 'Сбросить',
        'available-balance': 'Доступный баланс:',
        'enter-address': 'Введите адрес',
        'amount': 'Сумма',
        'fee': 'Комиссия',
        'recommended': 'рекомендовано',
        'loading': 'Загрузка...',
        'send-sure': 'Вы уверены?',
        'send-processing': 'Обработка...',
        'success': 'Успех',
        'failed': 'Неудача',
        'send-it': 'Да, отправить!',
        'cancel': 'Отменить',
        'send-warning': 'Вы в одном шаге от того, чтобы отправить',
        'send-warning-reverse': 'Это действие <strong>не может</strong> быть отменено. Вы в этом уверены?',
        'loading-utxo': 'Загрузка UTXOs...',
        'transaction-creation': 'Создание транзакции...',
        'transaction-broadcasted': 'Транзакция успешна транслирована: ',
        'address-type-changed': 'Тип адреса изменен на',
        'backend-switched': 'Бэкэнд изменен на',
        'backend-down': 'не доступен',
        'wallet-api': 'API бэкэнд кошелька',
        'open-wallet': 'Открыть Кошелек',
        'bad-utxo': 'Неподдерживаемый тип UTXO!',
        'balance-load-failed': 'Мы не можем загрузить баланс кошелька!',
        'not-enough-funds': 'У Вас недостаточно денежных средств для этой транзакции!',
        'not-valid-address': 'Вы должны указать действительный адрес!',
        'not-valid-amount': 'Вы должны указать действительную сумму!',
        'not-valid-fee': 'Вы должны указать действительную комиссию!',
        'bad-priv-key': 'Неверный приватный ключ WIF!',
        'not-enough-utxo': 'Недостаточно UTXO :(',
        'broadcast-failed': 'Не удалось транслировать транзакцию :(',
        'pass-not-match': 'Ваши пароли не совпадают!',
        'pass-too-short': 'Ваш пароль должен быть не меньше 10 символов!',
        'small-fee': 'Вы должны указать комиссию не меньше, чем',
        'scan-qr': 'Сканировать',
        'scan-modal-title': 'Сканер QR-кода',
        'webcam-message': 'Убедитесь, что веб-камера включена',
        'webcam-loading': 'Загрузка камеры...',
        'outputs-added': 'добавлен в выходы',
        'pin-login-title': 'Найден сохраненный кошелек',
        'pin-login-placeholder': 'Введите PIN для открытия',
        'pin-login-btn': 'Открыть',
        'pin-login-error': 'Неверный PIN, попробуйте снова.',
        'pin-login-forget': 'Забыть сохраненный кошелек',
        'settings-forget-wallet': 'Забыть сохраненный кошелек',
        'pin-title-default': 'PIN кошелька',
        'pin-input-placeholder': 'PIN (мин. 8 символов)',
        'pin-create-title': 'Создать PIN кошелька',
        'pin-create-desc': 'Придумайте надёжный PIN (минимум 8 символов: заглавная и строчная буква, цифра и специальный символ). Он понадобится каждый раз при открытии кошелька.',
        'pin-confirm-title': 'Подтвердить PIN',
        'pin-confirm-desc': 'Введите PIN ещё раз для подтверждения.',
        'pin-too-short': 'PIN должен содержать не менее 8 символов',
        'pin-mismatch': 'PIN-коды не совпадают. Попробуйте ещё раз.',
        'ok': 'ОК',
        'coin-control': 'Контроль монет',
        'coin-control-manual': 'Ручной выбор UTXO',
        'coin-control-select-all': 'Выбрать все зрелые',
        'coin-control-deselect-all': 'Снять выбор',
        'coin-control-confs': 'Подтв.',
        'coin-control-type': 'Тип',
        'coin-control-status': 'Статус',
        'coin-control-no-utxo': 'Нет UTXO',
        'coin-control-mature': 'зрелый',
        'coin-control-coinbase': 'coinbase',
        'coin-control-regular': 'обычный',
        'coin-control-matures-in': 'Созреет через',
        'coin-control-blocks': 'блоков',
        'coin-control-immature-title': 'Незрелый coinbase — нельзя потратить',
        'coin-control-selected': 'выбрано',
        'immature-mining': 'Незрелый (майнинг):',
        'immature-cannot-spend': 'пока нельзя потратить',
        'unconfirmed-balance': 'Не подтверждено:',
        'unconfirmed-mempool': 'ожидает в мемпуле',
        'history-loading': 'Загрузка истории…',
        'no-transactions': 'Транзакций пока нет',
        'history-failed': 'Не удалось загрузить историю',
        'history-network-error': 'Ошибка сети',
        'history-view-all': 'Посмотреть все',
        'history-on-explorer': 'транзакций в обозревателе',
        'history-conf': 'подтв.',
        'history-confirmed': 'подтверждено',
        'history-pending': 'ожидание',
        'copy-address': 'Скопировать адрес',
        'wallet-saved': 'Кошелёк сохранён. В следующий раз просто введите PIN.',
        'wallet-deleted': 'Сохранённый кошелёк удалён.',
        'identity-too-short': 'Идентификатор должен содержать не менее 3 символов.',
        'auto-locked': 'Кошелёк заблокирован из-за неактивности.',
        'theme-light': '☀️ Светлая',
        'theme-dark': '🌙 Тёмная',
        'theme-auto': '🔄 Авто',
        'redeem-script': 'Скрипт погашения (SegWit)',
        'open-seed': '🌱 Seed-фраза',
        'seed-btn-create': '✨ Создать новый кошелёк',
        'seed-btn-restore': '🔑 Восстановить из seed-фразы',
        'seed-step1-label': 'Шаг 1 из 2 — Ваша seed-фраза',
        'seed-write-warning': '⚠️ Запишите эти слова по порядку и храните в надёжном месте. Любой, кто знает эти слова, имеет доступ к вашим средствам.',
        'seed-print': 'Сохранить PNG',
        'seed-next': 'Далее →',
        'seed-step2-label': 'Шаг 2 из 2 — Проверка seed-фразы',
        'seed-verify-desc': 'Введите слова на указанных позициях, чтобы подтвердить, что вы их записали:',
        'seed-verify-error-msg': 'Неверные слова. Проверьте вашу фразу.',
        'seed-confirm-pin': 'Подтвердить и задать PIN',
        'seed-restore-title': 'Восстановление из seed-фразы',
        'seed-word-count': 'Количество слов:',
        'seed-restore-placeholder': 'Введите слова seed-фразы через пробел…',
        'seed-advanced': 'Дополнительно ▼',
        'seed-deriv-path': 'Путь деривации',
        'seed-deriv-hint': 'По умолчанию: BIP84 native SegWit. Измените для совместимости с Electrum/Ledger.',
        'seed-restore-btn': 'Восстановить и задать PIN',
        'seed-backup-label': 'Резервная копия seed-фразы',
        'seed-show-btn': '🌱 Показать seed-фразу (требуется PIN или Passkey)',
        'seed-hide-btn': '🔒 Скрыть',
        'seed-word-num': 'Слово',
        'seed-pin-modal-title': 'Введите PIN для просмотра seed-фразы',
        'seed-pin-modal-desc': 'Ваша seed-фраза будет показана на короткое время.',
        'seed-pin-cancel':  'Из-за отмены seed-фраза была перегенерирована в целях безопасности.',
        'privkey-pin-desc': 'Введите PIN для отображения приватного ключа',
        'seed-count-mismatch': 'Ожидается {n} слов, получено {m}.',
        'seed-invalid-phrase': 'Неверная seed-фраза. Проверьте орфографию и порядок слов.',
        'seed-deriv-error': 'Ошибка деривации:',
        'legacy-warn-password': '⚠️ <strong>Не рекомендуется.</strong> Этот метод получает ключ из хэша пароля и сохранён только для обратной совместимости. Пожалуйста, перенесите средства на кошелёк с Seed Phrase.',
        'legacy-warn-key': '⚠️ <strong>Не рекомендуется.</strong> Импорт необработанного закрытого ключа предоставляется только для совместимости. Используйте кошелёк с Seed Phrase для лучшей безопасности и возможности восстановления.',
        'seed-print-secret': 'Ваша seed-фраза — Храните в тайне!',
        'seed-print-warning': '⚠ Никогда не передавайте это изображение. Храните его только офлайн.',
        'seed-path-label': 'Путь:',
        'passkey-login-btn': 'Открыть с помощью Passkey',
        'passkey-settings-label': 'Passkey (Биометрическая разблокировка)',
        'passkey-use-instead': 'Использовать Passkey',
        'passkey-confirm-pin': 'Введите PIN для подтверждения личности перед настройкой Passkey',
        'passkey-enabled': '🔐 Passkey включён — теперь можно разблокировать биометрией',
        'passkey-disabled': 'Passkey отключён',
        'passkey-not-setup': 'Passkey не настроен',
        'passkey-prf-unsupported': 'Этот браузер не поддерживает расширение PRF, необходимое для Passkey',
        'passkey-decrypt-failed': 'Не удалось расшифровать через Passkey — попробуйте PIN',
        'passkey-error': 'Ошибка Passkey: ',
        'passkey-unsupported': 'Passkey не поддерживается на этом устройстве или браузере',
        'passkey-status-enabled': '✅ Включён — биометрическая разблокировка активна',
        'passkey-status-disabled': '🔒 Отключён — только PIN',
        'passkey-disable-btn': 'Отключить Passkey',
        'passkey-enable-btn': '🔐 Включить Passkey',
        'passkey-disable-confirm': 'Введите PIN или используйте Passkey для отключения',
        'pin-need-upper': 'Требуется заглавная буква (A–Z)',
        'pin-need-lower': 'Требуется строчная буква (a–z)',
        'pin-need-digit': 'Требуется цифра (0–9)',
        'pin-need-special': 'Требуется специальный символ (!@#$…)',
        'bip39-not-loaded': 'Библиотека BIP39 не загружена. Пожалуйста, перезагрузите страницу.',
        'seed-crypto-error': 'Криптографическая ошибка',
        'coin-control-unconfirmed-title': 'Невозможно потратить неподтверждённый выход',
    },
    'kr': {
        'lang-alias': '한국어',
        'open-regular': '일반 지갑',
        'open-key': '개인키로 열기',
        'disclaimer': '이 페이지는 javascript를 사용하여 주소를 생성하고 브라우저 내에서 거래에 서명합니다. 즉, 개인키를 절대 받지 않습니다. Github 소스 코드를 통하여 이를 검토할 수 있습니다.',
        'open-reminder': '<b>알림:</b> 계좌 정보를 안전하게 보관해주세요. 그렇지 않으면 코인을 영원히 잃을 수 있습니다.',
        'open': '열기',
        'home': '홈',
        'broadcast': '브로드캐스트',
        'settings': '설정',
        'email-address': '메일 주소',
        'password': '비밀번호',
        'password-confirm': '비밀번호 확인',
        'wif-key': 'WIF 개인키',
        'show': '표시하기',
        'hide': '숨기기',
        'address': '주소',
        'public-key': '공개키',
        'private-key': '개인키',
        'broadcast-transaction': '거래 브로드캐스트',
        'enter-transaction': '서명된 거래를 입력해주세요.',
        'address-type': '주소 형식',
        'wallet-backend': '지갑 백앤드',
        'update': '갱신',
        'version': '버전:',
        'wallet': '지갑',
        'close': '닫기',
        'send': '보내기',
        'history': '거래내역',
        'keys': '지갑키',
        'reset': '초기화',
        'available-balance': '이용 가능한 잔액:',
        'enter-address': '주소 입력',
        'amount': '전송량',
        'fee': '수수료',
        'recommended': '추천',
        'loading': '로드중...',
        'send-sure': '전송하시겠습니까?',
        'send-processing': '처리중...',
        'success': '성공',
        'failed': '실패',
        'send-it': '정상적으로 전송되었습니다!',
        'cancel': '취소',
        'send-warning': '다음과 같이 전송하고자 합니다',
        'send-warning-reverse': '이 작업을 시도하면 <strong>취소할 수 없습니다.</strong> 삭제 하시겠습니까?',
        'loading-utxo': 'UTXOs 로드중...',
        'transaction-creation': '거래 생성 중...',
        'transaction-broadcasted': '거래 브로드캐스트 성공: ',
        'address-type-changed': '정상적으로 주소 형식이 변경되었습니다.',
        'backend-switched': '정상적으로 백앤드가 변경되었습니다.',
        'backend-down': '사용할 수 없는 백앤드 입니다.',
        'wallet-api': '지갑 API 백앤드',
        'open-wallet': '지갑 열기',
        'bad-utxo': '지원되지 않는 UTXO 형식 입니다.',
        'balance-load-failed': '지갑 잔액 불러오기 실패!',
        'not-enough-funds': '전송에 필요한 잔액이 부족합니다.',
        'not-valid-address': '올바른 지갑 주소가 아닙니다.',
        'not-valid-amount': '올바른 전송량이 아닙니다.',
        'not-valid-fee': '올바른 수수료가 아닙니다.',
        'bad-priv-key': '잘못된 WIF개인키 입니다.',
        'not-enough-utxo': 'UTXO이 부족합니다. :(',
        'broadcast-failed': '거래 브로드캐스트에 실패하였습니다. :(',
        'pass-not-match': '비밀번호가 일치하지 않습니다.',
        'pass-too-short': '비밀번호는 10글자 이상 입력해주세요.',
        'small-fee': '최소수수료',
        'scan-qr': '스캔',
        'scan-modal-title': 'QR 코드 스캐너',
        'webcam-message': '웹캠이 활성화되었는지 확인하세요',
        'webcam-loading': '카메라 로딩 중...',
        'outputs-added': '출력에 추가됨',
        'pin-login-title': '저장된 지갑을 찾았습니다',
        'pin-login-placeholder': 'PIN을 입력하여 열기',
        'pin-login-btn': '열기',
        'pin-login-error': 'PIN이 틀렸습니다. 다시 시도하세요.',
        'pin-login-forget': '저장된 지갑 삭제',
        'settings-forget-wallet': '저장된 지갑 삭제',
        'pin-title-default': '지갑 PIN',
        'pin-input-placeholder': 'PIN (최소 8자)',
        'pin-create-title': '지갑 PIN 만들기',
        'pin-create-desc': '강력한 PIN을 선택하세요 (최소 8자: 대문자, 소문자, 숫자, 특수 문자 포함). 지갑을 열 때마다 사용됩니다.',
        'pin-confirm-title': 'PIN 확인',
        'pin-confirm-desc': '확인을 위해 PIN을 다시 입력하세요.',
        'pin-too-short': 'PIN은 최소 8자 이상이어야 합니다',
        'pin-mismatch': 'PIN이 일치하지 않습니다. 다시 시도하세요.',
        'ok': '확인',
        'coin-control': '코인 제어',
        'coin-control-manual': '수동 UTXO 선택',
        'coin-control-select-all': '성숙한 항목 모두 선택',
        'coin-control-deselect-all': '전체 선택 해제',
        'coin-control-confs': '확인수',
        'coin-control-type': '유형',
        'coin-control-status': '상태',
        'coin-control-no-utxo': 'UTXO 없음',
        'coin-control-mature': '사용 가능',
        'coin-control-coinbase': '코인베이스',
        'coin-control-regular': '일반',
        'coin-control-matures-in': '성숙까지',
        'coin-control-blocks': '블록',
        'coin-control-immature-title': '미성숙 코인베이스 — 사용 불가',
        'coin-control-selected': '선택됨',
        'immature-mining': '미성숙 (채굴):',
        'immature-cannot-spend': '아직 사용할 수 없음',
        'unconfirmed-balance': '미확인:',
        'unconfirmed-mempool': 'mempool 대기 중',
        'history-loading': '내역 로딩 중…',
        'no-transactions': '거래 내역이 없습니다',
        'history-failed': '내역 로드 실패',
        'history-network-error': '네트워크 오류',
        'history-view-all': '모든',
        'history-on-explorer': '거래 내역 보기 (탐색기)',
        'history-conf': '확인',
        'history-confirmed': '확인됨',
        'history-pending': '대기 중',
        'copy-address': '주소 복사',
        'wallet-saved': '지갑이 저장되었습니다. 다음에는 PIN만 입력하세요.',
        'wallet-deleted': '저장된 지갑이 삭제되었습니다.',
        'identity-too-short': '신원은 최소 3자 이상이어야 합니다.',
        'auto-locked': '비활동으로 인해 지갑이 잠겼습니다.',
        'theme-light': '☀️ 밝게',
        'theme-dark': '🌙 어둡게',
        'theme-auto': '🔄 자동',
        'redeem-script': '리딤 스크립트 (SegWit)',
        'open-seed': '🌱 시드 문구',
        'seed-btn-create': '✨ 새 지갑 만들기',
        'seed-btn-restore': '🔑 시드 문구로 복원',
        'seed-step1-label': '1단계 / 2단계 — 시드 문구',
        'seed-write-warning': '⚠️ 이 단어들을 순서대로 적어 안전한 곳에 보관하세요. 이 단어를 가진 누구든 자금을 통제할 수 있습니다.',
        'seed-print': 'PNG 저장',
        'seed-next': '다음 →',
        'seed-step2-label': '2단계 / 2단계 — 시드 문구 확인',
        'seed-verify-desc': '올바르게 저장했는지 확인하기 위해 해당 위치의 단어를 입력하세요:',
        'seed-verify-error-msg': '단어가 틀렸습니다. 문구를 확인해 주세요.',
        'seed-confirm-pin': '확인 및 PIN 설정',
        'seed-restore-title': '시드 문구로 복원',
        'seed-word-count': '단어 수:',
        'seed-restore-placeholder': '시드 문구 단어를 공백으로 구분하여 입력…',
        'seed-advanced': '고급 ▼',
        'seed-deriv-path': '파생 경로',
        'seed-deriv-hint': '기본값: BIP84 native SegWit. Electrum/Ledger 호환성을 위해 변경 가능.',
        'seed-restore-btn': '복원 및 PIN 설정',
        'seed-backup-label': '시드 문구 백업',
        'seed-show-btn': '🌱 시드 문구 표시 (PIN 또는 패스키 필요)',
        'seed-hide-btn': '🔒 숨기기',
        'seed-word-num': '단어',
        'seed-pin-modal-title': '시드 문구 확인을 위해 PIN 입력',
        'seed-pin-modal-desc': '시드 문구가 잠시 표시됩니다.',
        'seed-pin-cancel':  '취소로 인해 보안상의 이유로 시드가 재생성되었습니다.',
        'privkey-pin-desc': '개인 키를 표시하려면 PIN을 입력하세요',
        'seed-count-mismatch': '{n}개의 단어가 필요하지만 {m}개가 입력되었습니다.',
        'seed-invalid-phrase': '유효하지 않은 시드 문구입니다. 철자와 단어 순서를 확인하세요.',
        'seed-deriv-error': '파생 오류:',
        'legacy-warn-password': '⚠️ <strong>권장하지 않습니다.</strong> 이 방법은 비밀번호 해시에서 키를 파생하며 하위 호환성만을 위해 유지됩니다. 시드 구문 지갑으로 자금을 이전하세요.',
        'legacy-warn-key': '⚠️ <strong>권장하지 않습니다.</strong> 원시 개인 키 가져오기는 호환성만을 위해 제공됩니다. 더 나은 보안과 복구 가능성을 위해 시드 구문 지갑을 사용하세요.',
        'seed-print-secret': '당신의 시드 구문 — 비밀로 유지하세요!',
        'seed-print-warning': '⚠ 이 이미지를 절대 공유하지 마십시오. 오프라인으로만 보관하십시오.',
        'seed-path-label': '경로:',
        'passkey-login-btn': '패스키로 열기',
        'passkey-settings-label': '패스키 (생체 인증 잠금 해제)',
        'passkey-use-instead': '패스키 사용',
        'passkey-confirm-pin': '패스키를 설정하기 전에 PIN으로 본인을 확인하세요',
        'passkey-enabled': '🔐 패스키 활성화됨 — 이제 생체 인증으로 잠금 해제할 수 있습니다',
        'passkey-disabled': '패스키가 비활성화되었습니다',
        'passkey-not-setup': '패스키가 설정되지 않았습니다',
        'passkey-prf-unsupported': '이 브라우저는 패스키에 필요한 PRF 확장을 지원하지 않습니다',
        'passkey-decrypt-failed': '패스키 복호화 실패 — PIN을 시도하세요',
        'passkey-error': '패스키 오류: ',
        'passkey-unsupported': '이 기기 또는 브라우저에서 패스키를 지원하지 않습니다',
        'passkey-status-enabled': '✅ 활성화됨 — 생체 인증 잠금 해제 사용 중',
        'passkey-status-disabled': '🔒 비활성화됨 — PIN만 사용',
        'passkey-disable-btn': '패스키 비활성화',
        'passkey-enable-btn': '🔐 패스키 활성화',
        'passkey-disable-confirm': '패스키를 비활성화하려면 PIN을 입력하거나 패스키를 사용하세요',
        'pin-need-upper': '대문자(A–Z)가 포함되어야 합니다',
        'pin-need-lower': '소문자(a–z)가 포함되어야 합니다',
        'pin-need-digit': '숫자(0–9)가 포함되어야 합니다',
        'pin-need-special': '특수 문자(!@#$…)가 포함되어야 합니다',
        'bip39-not-loaded': 'BIP39 라이브러리가 로드되지 않았습니다. 페이지를 다시 로드해주세요.',
        'seed-crypto-error': '암호화 오류',
        'coin-control-unconfirmed-title': '미확인 출력은 사용할 수 없습니다',
    },
    'de': {
        'lang-alias': 'Deutsch',
        'open-regular': 'Reguläre Wallet',
        'open-key': 'Mit Schlüssel öffnen',
        'disclaimer': 'Dieses Wallet benutzt JavaScript um Deine Adressen zu generieren und Transaktionen im Browser zu signieren. Zu keinem Zeitpunkt wird hierbei dein Privatschlüssel dauerhaft gespeichert!! Zur Überprüfung kann der Quellcode jederzeit im GitHub eingesehen werden.',
        'open-reminder': '<b>Notice:</b> Sorge bitte dafür dich an deine Kontodaten erinnern zu können um nicht den Zugriff zu deinem Konto und dessen Guthaben zu verlieren!',
        'open': 'Öffnen',
        'home': 'Startseite',
        'broadcast': 'Übertragung',
        'settings': 'Einstellungen',
        'email-address': 'Email Addresse',
        'password': 'Passwort',
        'password-confirm': 'Passwort bestätigen',
        'wif-key': 'Privater Schlüssel (WIF)',
        'show': 'Anzeigen',
        'hide': 'Verbergen',
        'address': 'Addresse',
        'public-key': 'Öffentlicher Schlüssel',
        'private-key': 'Privater Schlüssel',
        'broadcast-transaction': 'Transaktion senden',
        'enter-transaction': 'Signierte Transaktion eintragen',
        'address-type': 'Addresstyp',
        'wallet-backend': 'Wallet Backend',
        'update': 'Aktualisieren',
        'version': 'Version:',
        'wallet': 'Wallet',
        'close': 'Schließen',
        'send': 'Senden',
        'history': 'Verlauf',
        'keys': 'Schlüssel',
        'reset': 'Reset',
        'available-balance': 'Verfügbares Guthaben:',
        'enter-address': 'Adresse eingeben',
        'amount': 'Betrag',
        'fee': 'Transaktionsgebühr',
        'recommended': 'empfohlen',
        'loading': 'Lade...',
        'send-sure': 'Bist du sicher?',
        'send-processing': 'Verarbeitung läuft...',
        'success': 'Aktion erfolgreich',
        'failed': 'Aktion fehlgeschlagen',
        'send-it': 'Ja, bitte senden!',
        'cancel': 'Abbruch',
        'send-warning': 'Du bist dabei, eine Zahlung zu senden',
        'send-warning-reverse': 'Diese Aktion kann<strong>nicht rückgängig</strong> gemacht werden. Bist Du wirklich sicher?',
        'loading-utxo': 'Lade UTXOen...',
        'transaction-creation': 'Transaktion wird erstellt...',
        'transaction-broadcasted': 'Transaktion erfolgreich gesendet: ',
        'address-type-changed': 'Adresstyp geändert in',
        'backend-switched': 'Backend geändert zu',
        'backend-down': 'scheint gerade nicht verfügbar zu sein',
        'wallet-api': 'Wallet API backend',
        'open-wallet': 'Wallet öffnen',
        'bad-utxo': 'Nicht unterstützter UTXO Typ!',
        'balance-load-failed': 'Kontostand konnte nicht geladen werden!',
        'not-enough-funds': 'Dein Guthaben ist für diese Transaktion nicht ausreichend!',
        'not-valid-address': 'Bitte gib eine gültige Adresse ein!',
        'not-valid-amount': 'Bitte gib einen gültigen Betrag ein!',
        'not-valid-fee': 'Bitte gib eine gültige Transaktionsgebühr ein!',
        'bad-priv-key': 'Ungültiger oder falscher WIF-Schlüssel',
        'not-enough-utxo': 'Nicht genügend UTXO :(',
        'broadcast-failed': 'Sendung der Transaktion fehlgeschlagen :(',
        'pass-not-match': 'Die von Dir eingegebenen Passwörter stimmen nicht überein!',
        'pass-too-short': 'Die Länge Deines Passworts muss mindestens 10 Zeichen betragen!',
        'small-fee': 'sollte nicht weniger betragen als',
        'scan-qr': 'Scannen',
        'scan-modal-title': 'QR-Code-Scanner',
        'webcam-message': 'Bitte stellen Sie sicher, dass eine Webcam aktiviert ist',
        'webcam-loading': 'Kamera wird geladen...',
        'outputs-added': 'zu Ausgängen hinzugefügt',
        'pin-login-title': 'Gespeicherte Wallet gefunden',
        'pin-login-placeholder': 'PIN zum Öffnen eingeben',
        'pin-login-btn': 'Öffnen',
        'pin-login-error': 'Falsche PIN, erneut versuchen.',
        'pin-login-forget': 'Gespeicherte Wallet vergessen',
        'settings-forget-wallet': 'Gespeicherte Wallet vergessen',
        'pin-title-default': 'Wallet-PIN',
        'pin-input-placeholder': 'PIN (mind. 8 Zeichen)',
        'pin-create-title': 'Wallet-PIN erstellen',
        'pin-create-desc': 'Wähle eine starke PIN (mind. 8 Zeichen: Großbuchstabe, Kleinbuchstabe, Ziffer und Sonderzeichen). Du benötigst sie jedes Mal beim Öffnen der Wallet.',
        'pin-confirm-title': 'PIN bestätigen',
        'pin-confirm-desc': 'Gib deine PIN zur Bestätigung erneut ein.',
        'pin-too-short': 'Die PIN muss mindestens 8 Zeichen lang sein',
        'pin-mismatch': 'Die PINs stimmen nicht überein. Versuche es erneut.',
        'ok': 'OK',
        'coin-control': 'Münzkontrolle',
        'coin-control-manual': 'Manuelle UTXO-Auswahl',
        'coin-control-select-all': 'Alle reifen auswählen',
        'coin-control-deselect-all': 'Auswahl aufheben',
        'coin-control-confs': 'Best.',
        'coin-control-type': 'Typ',
        'coin-control-status': 'Status',
        'coin-control-no-utxo': 'Keine UTXOs',
        'coin-control-mature': 'reif',
        'coin-control-coinbase': 'Coinbase',
        'coin-control-regular': 'regulär',
        'coin-control-matures-in': 'Reift in',
        'coin-control-blocks': 'Blöcken',
        'coin-control-immature-title': 'Unreifer Coinbase — kann nicht ausgegeben werden',
        'coin-control-selected': 'ausgewählt',
        'immature-mining': 'Unreif (Mining):',
        'immature-cannot-spend': 'noch nicht ausgebbar',
        'unconfirmed-balance': 'Unbestätigt:',
        'unconfirmed-mempool': 'ausstehend im Mempool',
        'history-loading': 'Verlauf wird geladen…',
        'no-transactions': 'Noch keine Transaktionen',
        'history-failed': 'Verlauf konnte nicht geladen werden',
        'history-network-error': 'Netzwerkfehler',
        'history-view-all': 'Alle',
        'history-on-explorer': 'Transaktionen im Explorer anzeigen',
        'history-conf': 'Best.',
        'history-confirmed': 'bestätigt',
        'history-pending': 'ausstehend',
        'copy-address': 'Adresse kopieren',
        'wallet-saved': 'Wallet gespeichert. Beim nächsten Mal reicht die PIN.',
        'wallet-deleted': 'Gespeicherte Wallet gelöscht.',
        'identity-too-short': 'Die Identität muss mindestens 3 Zeichen lang sein.',
        'auto-locked': 'Wallet wegen Inaktivität gesperrt.',
        'theme-light': '☀️ Hell',
        'theme-dark': '🌙 Dunkel',
        'theme-auto': '🔄 Auto',
        'redeem-script': 'Einlöseskript (SegWit)',
        'open-seed': '🌱 Seed-Phrase',
        'seed-btn-create': '✨ Neue Wallet erstellen',
        'seed-btn-restore': '🔑 Aus Seed-Phrase wiederherstellen',
        'seed-step1-label': 'Schritt 1 von 2 — Ihre Seed-Phrase',
        'seed-write-warning': '⚠️ Schreiben Sie diese Wörter in der richtigen Reihenfolge auf und bewahren Sie sie sicher auf. Jeder mit diesen Wörtern hat Kontrolle über Ihre Mittel.',
        'seed-print': 'PNG speichern',
        'seed-next': 'Weiter →',
        'seed-step2-label': 'Schritt 2 von 2 — Seed-Phrase verifizieren',
        'seed-verify-desc': 'Geben Sie die Wörter an diesen Positionen ein, um zu bestätigen, dass Sie sie gespeichert haben:',
        'seed-verify-error-msg': 'Falsche Wörter. Bitte überprüfen Sie Ihre Phrase.',
        'seed-confirm-pin': 'Bestätigen &amp; PIN setzen',
        'seed-restore-title': 'Aus Seed-Phrase wiederherstellen',
        'seed-word-count': 'Wortanzahl:',
        'seed-restore-placeholder': 'Geben Sie die Wörter Ihrer Seed-Phrase durch Leerzeichen getrennt ein…',
        'seed-advanced': 'Erweitert ▼',
        'seed-deriv-path': 'Ableitungspfad',
        'seed-deriv-hint': 'Standard: BIP84 native SegWit. Ändern für Electrum/Ledger-Kompatibilität.',
        'seed-restore-btn': 'Wiederherstellen &amp; PIN setzen',
        'seed-backup-label': 'Seed-Phrase Sicherung',
        'seed-show-btn': '🌱 Seed-Phrase anzeigen (PIN oder Passkey erforderlich)',
        'seed-hide-btn': '🔒 Ausblenden',
        'seed-word-num': 'Wort',
        'seed-pin-modal-title': 'PIN eingeben, um Seed-Phrase anzuzeigen',
        'seed-pin-modal-desc': 'Ihre Seed-Phrase wird kurz angezeigt.',
        'seed-pin-cancel':  'Wegen Abbruch wurde der Seed aus Sicherheitsgründen neu generiert.',
        'privkey-pin-desc': 'PIN eingeben, um den privaten Schlüssel anzuzeigen',
        'seed-count-mismatch': '{n} Wörter erwartet, {m} erhalten.',
        'seed-invalid-phrase': 'Ungültige Seed-Phrase. Überprüfen Sie Schreibweise und Wortreihenfolge.',
        'seed-deriv-error': 'Ableitungsfehler:',
        'legacy-warn-password': '⚠️ <strong>Nicht empfohlen.</strong> Diese Methode leitet einen Schlüssel aus einem Passwort-Hash ab und wird nur aus Gründen der Abwärtskompatibilität beibehalten. Bitte migrieren Sie Ihre Mittel zu einem Seed-Phrase-Wallet.',
        'legacy-warn-key': '⚠️ <strong>Nicht empfohlen.</strong> Der Import eines rohen privaten Schlüssels wird nur aus Kompatibilitätsgründen bereitgestellt. Verwenden Sie ein Seed-Phrase-Wallet für bessere Sicherheit und Wiederherstellbarkeit.',
        'seed-print-secret': 'Ihre Seed-Phrase — Geheim halten!',
        'seed-print-warning': '⚠ Geben Sie dieses Bild niemals weiter. Nur offline aufbewahren.',
        'seed-path-label': 'Pfad:',
        'passkey-login-btn': 'Mit Passkey öffnen',
        'passkey-settings-label': 'Passkey (Biometrische Entsperrung)',
        'passkey-use-instead': 'Passkey verwenden',
        'passkey-confirm-pin': 'PIN eingeben, um Identität vor der Passkey-Einrichtung zu bestätigen',
        'passkey-enabled': '🔐 Passkey aktiviert — du kannst jetzt per Biometrie entsperren',
        'passkey-disabled': 'Passkey deaktiviert',
        'passkey-not-setup': 'Passkey nicht eingerichtet',
        'passkey-prf-unsupported': 'Dieser Browser unterstützt die für Passkey erforderliche PRF-Erweiterung nicht',
        'passkey-decrypt-failed': 'Passkey-Entschlüsselung fehlgeschlagen — bitte PIN versuchen',
        'passkey-error': 'Passkey-Fehler: ',
        'passkey-unsupported': 'Passkey wird auf diesem Gerät oder Browser nicht unterstützt',
        'passkey-status-enabled': '✅ Aktiviert — biometrische Entsperrung aktiv',
        'passkey-status-disabled': '🔒 Deaktiviert — nur PIN',
        'passkey-disable-btn': 'Passkey deaktivieren',
        'passkey-enable-btn': '🔐 Passkey aktivieren',
        'passkey-disable-confirm': 'PIN eingeben oder Passkey verwenden, um Passkey zu deaktivieren',
        'pin-need-upper': 'Muss einen Großbuchstaben enthalten (A–Z)',
        'pin-need-lower': 'Muss einen Kleinbuchstaben enthalten (a–z)',
        'pin-need-digit': 'Muss eine Ziffer enthalten (0–9)',
        'pin-need-special': 'Muss ein Sonderzeichen enthalten (!@#$…)',
        'bip39-not-loaded': 'BIP39-Bibliothek nicht geladen. Bitte die Seite neu laden.',
        'seed-crypto-error': 'Kryptografischer Fehler',
        'coin-control-unconfirmed-title': 'Unbestätigten Ausgang kann nicht ausgegeben werden',
    }
}
