var walletLanguages = {
	'en': {
		'lang-alias': 'English',
		'wallet-title': 'Wallet',
		'open-regular': 'Regular wallet',
		'open-key': 'Open by key',
		'disclaimer': 'This page uses javascript to generate your addresses and sign your transactions within your browser, this means we never receive your private keys, this can be independently verified by reviewing the source code on Github.',
		'open-reminder': '<b>Notice:</b> Please make sure that you remember your account details, otherwise you may lose access to your funds.',
		'open': 'Open',
		'home': 'Home',
		'create': 'Create',
		'broadcast': 'Broadcast',
		'settings': 'Settings',
		'email-address': 'Email address',
		'password': 'Password',
		'password-confirm': 'Confirm password',
		'generate-question': 'Still don\'t have wallet?',
		'generate-it': '<a href="#/create">Generate</a> it!',
		'wif-key': 'WIF Private key',
		'create-wallet': 'Create wallet',
		'show': 'Show',
		'hide': 'Hide',
		'address': 'Address',
		'public-key': 'Public Key',
		'private-key': 'Private Key',
		'broadcast-transaction': 'Broadcast transaction',
		'enter-transaction': 'Enter your signed transaction',
		'wallet-settings': 'Wallet settings',
		'address-type': 'Address Type',
		'wallet-backend': 'Wallet Backend',
		'update': 'Update',
		'wallet-language': 'Wallet Language',
		'version': 'Version:',
		'wallet': 'Wallet',
		'close': 'Close',
		'send': 'Send',
		'history': 'History',
		'keys': 'Keys',
		'reset': 'Reset',
		'available-balance': 'Available balance:',
		'enter-address': 'Enter address',
		'amount': 'Amount',
		'fee': 'Fee',
		'recommended': 'recommended',
		'loading': 'Loading...',
		'send-sure': 'Are you sure?',
		'send-processing': 'Processing...',
		'success': 'Success',
		'failed': 'Failed',
		'send-it': 'Yes, send it!',
		'cancel': 'Cancel',
		'send-warning': 'You are one step away from sending',
		'send-warning-reverse': 'This action <strong>cannot</strong> be reversed. Are you sure about this?',
		'loading-utxo': 'Loading UTXOs...',
		'transaction-creation': 'Creating transaction...',
		'transaction-broadcasted': 'Transaction successfully broadcasted: ',
		'close': 'Close',
		'address-type-changed': 'Address type changed to',
		'backend-switched': 'Backend is switched to',
		'backend-down': 'don\'t seems to be available',
		'wallet-api': 'Wallet API backend',
		'open-wallet': 'Open Wallet',
		'bad-utxo': 'Unsupported UTXO type!',
		'balance-load-failed': 'We couldn\'t load wallet balance!',
		'not-enough-funds': 'You don\'t have enough funds for this transaction!',
		'not-valid-address': 'You must specify valid address!',
		'not-valid-amount': 'You must specify valid amount!',
		'not-valid-fee': 'You must specify valid fee!',
		'bad-priv-key': 'Bad WIF private key!',
		'not-enough-utxo': 'Not enough UTXO :(',
		'broadcast-failed': 'Transaction broadcast failed :(',
		'pass-not-match': 'Your passwords do not match!',
		'pass-too-short': 'Your password must be at least 10 chars long!',
		'bad-email': 'Your email address doesn\'t appear to be valid!',
		'small-fee': 'You should specify fee not less than',
		'scan-qr': 'Scan',
		'scan-modal-title': 'QR Code scanner',
		'webcam-message': 'Please make sure you have a webcam enabled',
		'webcam-loading': 'Loading camera...',
		'outputs-added': 'added to outputs',
		'pin-login-title': 'Saved wallet found',
		'pin-login-placeholder': 'Enter PIN to open',
		'pin-login-btn': 'Open',
		'pin-login-error': 'Wrong PIN, try again.',
		'pin-login-manual': 'Enter credentials manually',
		'pin-login-forget': 'Forget saved wallet',
		'saved-wallet-hint-prefix': 'Saved wallet found. ',
		'saved-wallet-open': 'Open with PIN',
		'saved-wallet-or': ' or ',
		'saved-wallet-forget': 'forget it',
		'saved-wallet-label': 'Saved wallet',
		'settings-forget-wallet': 'Forget saved wallet',
		'pin-title-default': 'Wallet PIN',
		'pin-input-placeholder': 'PIN (min 6 digits)',
		'pin-save-title': 'Save wallet',
		'pin-save-desc': 'Enter a PIN to save your wallet. Next time you will only need the PIN to open it.',
		'pin-create-title': 'Create wallet PIN',
		'pin-create-desc': 'Choose a PIN (minimum 6 characters). You will use it every time you open the wallet.',
		'pin-confirm-title': 'Confirm PIN',
		'pin-confirm-desc': 'Re-enter your PIN to confirm.',
		'pin-too-short': 'PIN must be at least 6 characters.',
		'pin-mismatch': 'PINs do not match. Try again.',
		'ok': 'OK',
		'coin-control': 'Coin Control',
		'coin-control-manual': 'Manual UTXO selection',
		'coin-control-select-all': 'Select all mature',
		'coin-control-confs': 'Confs',
		'coin-control-type': 'Type',
		'coin-control-status': 'Status',
		'coin-control-no-utxo': 'No UTXOs',
		'coin-control-mature': 'mature',
		'coin-control-coinbase': 'coinbase',
		'coin-control-regular': 'regular',
		'coin-control-matures-in': 'Matures in',
		'coin-control-blocks': 'blocks',
		'coin-control-immature-title': 'Immature coinbase — cannot spend',
		'coin-control-selected': 'selected',
		'immature-mining': 'Immature (mining):',
		'immature-cannot-spend': 'cannot spend yet',
		'history-loading': 'Loading history…',
		'no-transactions': 'No transactions yet',
		'history-failed': 'Failed to load history',
		'history-network-error': 'Network error',
		'history-view-all': 'View all',
		'history-on-explorer': 'transactions on explorer',
		'history-conf': 'conf',
		'history-confirmed': 'confirmed',
		'history-pending': 'pending',
		'copy-address': 'Copy address',
		'wallet-saved': 'Wallet saved. Next time just enter your PIN.',
		'wallet-deleted': 'Saved wallet deleted.',
		'wallet-corrupted': 'Saved wallet is corrupted. Please re-open manually.',
		'identity-too-short': 'Identity must be at least 3 characters.',
		'redeem-script': 'Redeem Script (SegWit)'
	},
	'uk': {
		'lang-alias': 'Українська',
		'wallet-title': 'Гаманець',
		'open-regular': 'Звичайний гаманець',
		'open-key': 'Відкрити ключем',
		'disclaimer': 'Ця сторінка використовує javascript для генерації ваших адрес та підпису транзакцій всередині браузера, це означає, що ми ніколи не отримуємо ваші приватні ключі, це можна перевірити незалежно, переглянувши вихідний код на Github.',
		'open-reminder': '<b>Увага:</b> Будь ласка переконайтесь, що ви запам\'ятали дані вашого акаунту, інакше ви можете втратити доступ до ваших коштів.',
		'open': 'Відкрити',
		'home': 'Домівка',
		'create': 'Створити',
		'broadcast': 'Транслювати',
		'settings': 'Налаштування',
		'email-address': 'Електронна пошта',
		'password': 'Пароль',
		'password-confirm': 'Підтвердіть пароль',
		'generate-question': 'Все ще не маєте гаманця?',
		'generate-it': '<a href="#/create">Згенеруйте</a> його!',
		'wif-key': 'Приватний ключ WIF',
		'create-wallet': 'Створити гаманець',
		'show': 'Показати',
		'hide': 'Сховати',
		'address': 'Адреса',
		'public-key': 'Публічний Ключ',
		'private-key': 'Приватний Ключ',
		'broadcast-transaction': 'Транслювати транзакцію',
		'enter-transaction': 'Введіть вашу підписану транзакцію',
		'wallet-settings': 'Налаштування гаманця',
		'address-type': 'Тип Адреси',
		'wallet-backend': 'Бекенд Гаманця',
		'update': 'Оновити',
		'wallet-language': 'Мова Гаманця',
		'version': 'Версія:',
		'wallet': 'Гаманець',
		'close': 'Закрити',
		'send': 'Надіслати',
		'history': 'Історія',
		'keys': 'Ключі',
		'reset': 'Скинути',
		'available-balance': 'Доступний баланс:',
		'enter-address': 'Введіть адресу',
		'amount': 'Сума',
		'fee': 'Комісія',
		'recommended': 'рекомендовано',
		'loading': 'Завантаження...',
		'send-sure': 'Ви впевенені?',
		'send-processing': 'Обробка...',
		'success': 'Успіх',
		'failed': 'Невдача',
		'send-it': 'Так, надіслати!',
		'cancel': 'Скасувати',
		'send-warning': 'Ви в одному кроці від того, щоб надіслати',
		'send-warning-reverse': 'Ця дія <strong>не може</strong> бути скасованою. Ви впевнені?',
		'loading-utxo': 'Завантаження UTXOs...',
		'transaction-creation': 'Створення транзакції...',
		'transaction-broadcasted': 'Транзакція успішно надіслана: ',
		'close': 'Закрити',
		'address-type-changed': 'Тип адрес змінений на',
		'backend-switched': 'Бекенд змінений на',
		'backend-down': 'виглядає мертвим',
		'wallet-api': 'API Бекенд гаманця',
		'open-wallet': 'Відкрити Гаманець',
		'bad-utxo': 'Непідтримуваний тип UTXO!',
		'balance-load-failed': 'Нам не вдалося завантажити баланс вашого гаманця!',
		'not-enough-funds': 'У вас не достатньо коштів для цієї транзакції!',
		'not-valid-address': 'Ви маєте ввести дійсну адресу!',
		'not-valid-amount': 'Ви маєте ввести дійсну суму!',
		'not-valid-fee': 'Ви маєте ввести дійсну комісію!',
		'bad-priv-key': 'Недійсний WIF приватний ключ WIF!',
		'not-enough-utxo': 'Не достатньо UTXO :(',
		'broadcast-failed': 'Не вдалося транслювати транзакцію :(',
		'pass-not-match': 'Паролі не не збігаються!',
		'pass-too-short': 'Ваш пароль повинен бути не менше 10 символів!',
		'bad-email': 'Схоже, що ви ввели не дійсну поштову скриньку!',
		'small-fee': 'Ви маєте задати комісію не менше ніж',
		'scan-qr': 'Сканувати',
		'scan-modal-title': 'Зчитувач QR коду',
		'webcam-message': 'Будь ласка, переконайтеся, що у вас увімкнена веб-камера',
		'webcam-loading': 'Завантаження камери...',
		'outputs-added': 'додано до виходів',
		'pin-login-title': 'Знайдено збережений гаманець',
		'pin-login-placeholder': 'Введіть PIN для відкриття',
		'pin-login-btn': 'Відкрити',
		'pin-login-error': 'Неправильний PIN, спробуйте ще раз.',
		'pin-login-manual': 'Ввести дані вручну',
		'pin-login-forget': 'Забути збережений гаманець',
		'saved-wallet-hint-prefix': 'Знайдено збережений гаманець. ',
		'saved-wallet-open': 'Відкрити з PIN',
		'saved-wallet-or': ' або ',
		'saved-wallet-forget': 'забути його',
		'saved-wallet-label': 'Збережений гаманець',
		'settings-forget-wallet': 'Забути збережений гаманець',
		'pin-title-default': 'PIN гаманця',
		'pin-input-placeholder': 'PIN (мін. 6 цифри)',
		'pin-save-title': 'Зберегти гаманець',
		'pin-save-desc': 'Введіть PIN, щоб зберегти гаманець. Наступного разу вам знадобиться лише PIN для входу.',
		'pin-create-title': 'Створити PIN гаманця',
		'pin-create-desc': 'Придумайте PIN (мінімум 6 символів). Він знадобиться кожного разу при відкритті гаманця.',
		'pin-confirm-title': 'Підтвердити PIN',
		'pin-confirm-desc': 'Введіть PIN ще раз для підтвердження.',
		'pin-too-short': 'PIN має містити щонайменше 6 символів.',
		'pin-mismatch': 'PIN-коди не збігаються. Спробуйте ще раз.',
		'ok': 'ОК',
		'coin-control': 'Контроль монет',
		'coin-control-manual': 'Ручний вибір UTXO',
		'coin-control-select-all': 'Вибрати всі зрілі',
		'coin-control-confs': 'Підтв.',
		'coin-control-type': 'Тип',
		'coin-control-status': 'Статус',
		'coin-control-no-utxo': 'Немає UTXO',
		'coin-control-mature': 'зрілий',
		'coin-control-coinbase': 'coinbase',
		'coin-control-regular': 'звичайний',
		'coin-control-matures-in': 'Дозріє за',
		'coin-control-blocks': 'блоків',
		'coin-control-immature-title': 'Незрілий coinbase — неможливо витратити',
		'coin-control-selected': 'обрано',
		'immature-mining': 'Незрілий (майнінг):',
		'immature-cannot-spend': 'ще не можна витратити',
		'history-loading': 'Завантаження історії…',
		'no-transactions': 'Транзакцій ще немає',
		'history-failed': 'Не вдалося завантажити історію',
		'history-network-error': 'Помилка мережі',
		'history-view-all': 'Переглянути всі',
		'history-on-explorer': 'транзакцій в огляднику',
		'history-conf': 'підтв.',
		'history-confirmed': 'підтверджено',
		'history-pending': 'очікується',
		'copy-address': 'Скопіювати адресу',
		'wallet-saved': 'Гаманець збережено. Наступного разу просто введіть PIN.',
		'wallet-deleted': 'Збережений гаманець видалено.',
		'wallet-corrupted': 'Збережений гаманець пошкоджено. Будь ласка, відкрийте вручну.',
		'identity-too-short': 'Ідентифікатор має містити щонайменше 3 символи.',
		'redeem-script': 'Скрипт погашення (SegWit)'
	},
	'id': {
		'lang-alias': 'Indonesian',
		'wallet-title' : 'Wallet',
		'open-regular': 'Buka dompet',
		'open-key': 'Buka dengan kunci',
		'disclaimer': 'Halaman ini menggunakan javascript untuk menghasilkan alamat dompet dan menandatangani transaksi Anda, ini berarti kami tidak pernah menerima kunci domprt pribadi Anda, ini diverifikasi secara terpisah dengan melihat sumber code di Github.',
		'open-reminder': '<b>Perhatikan:</b> Pastikan Anda mencadangkan detail dompet anda, jika tidak, Anda dapat kehilangan akses ke dana Anda.',
		'open': 'Buka',
		'home': 'Halaman depan',
		'create': 'Membuat',
		'broadcast': 'Siaran',
		'settings': 'Pengaturan',
		'email-address': 'Alamat Email',
		'password': 'Kata Kunci',
		'password-confirm': 'Konfirmasi Kata Kunci',
		'generate-question': 'sudah punya dompet belum punya dompet?',
		'generate-it': '<a href="#/create">Membuat</a> dompet!',
		'wif-key': 'WIF Kunci Pribadi',
		'create-wallet': 'Membuat Dompet',
		'show': 'Tunjukan',
		'hide': 'Sembunyikan',
		'address': 'Alamat',
		'public-key': 'Kunci Publik',
		'private-key': 'Kunci Pribadi',
		'broadcast-transaction': 'Siaran transaksi',
		'enter-transaction': 'masuk transaksi',
		'wallet-settings': 'Pengaturan Dompet',
		'address-type': 'Tipe Alamat',
		'wallet-backend': 'Backend Dompet',
		'update': 'Pembaharuan',
		'wallet-language': 'Bahasa dompet',
		'version': 'Versi:',
		'wallet': 'Dompet',
		'close': 'Tutup',
		'send': 'Kirim',
		'history': 'Riwayat',
		'keys': 'Kunci',
		'reset': 'Mulai ulang',
		'available-balance': 'Saldo tersedia:',
		'enter-address': 'Masukan Alamat',
		'amount': 'Jumlah',
		'fee': 'Biaya',
		'recommended': 'Rekomendasi',
		'loading': 'Memuat...',
		'send-sure': 'Apakah kamu Yakin?',
		'send-processing': 'Memproses...',
		'success': 'Sukses',
		'failed': 'Gagal',
		'send-it': 'Ya, Kirim sekarang!',
		'cancel': 'Batalkan',
		'send-warning': 'Tinggal selangkah lagi',
		'send-warning-reverse': 'Tetap kirim <strong>Batalkan</strong> bisa kembali. Apa kamu sudah yakin?',
		'loading-utxo': 'Memuat UTXOs...',
		'transaction-creation': 'Membuat Transaksi...',
		'transaction-broadcasted': 'Transaksi berhasil dikirim: ',
		'close': 'Tutup',
		'address-type-changed': 'Ganti tipe alamat',
		'backend-switched': 'Backend berpindah ke',
		'backend-down': 'Backend sepertinya tidak ada',
		'wallet-api': 'Dompet API',
		'open-wallet': 'Buka Dompet',
		'bad-utxo': 'Tidak mendukung tipe UTXO!',
		'balance-load-failed': 'Kami tidak bisa menampilkan jumlah saldo!',
		'not-enough-funds': 'Kamu tidak punya cukup saldo untuk transaksi ini!',
		'not-valid-address': 'Kamu harus memasukkan wallet yang benar!',
		'not-valid-amount': 'Kamu harus memasukkan jumlah yang benar!',
		'not-valid-fee': 'Kamu harus memasukkan biaya yang benar!',
		'bad-priv-key': 'Kunci Pribadi Salah!',
		'not-enough-utxo': 'Tidak Cukup UTXO :(',
		'broadcast-failed': 'Siaran transaksi gagal :(',
		'pass-not-match': 'Password anda tidak cocok!',
		'pass-too-short': 'Kata sandi Anda setidaknya harus sepanjang 10 karakter!',
		'bad-email': 'Alamat email Anda tampaknya tidak valid!',
		'small-fee': 'Biaya terlalu kecil',
		'scan-qr': 'Pindai',
		'scan-modal-title': 'Pemindai QR',
		'webcam-message': 'Pastikan webcam Anda aktif',
		'webcam-loading': 'Memuat kamera...',
		'outputs-added': 'ditambahkan ke output',
		'pin-login-title': 'Dompet tersimpan ditemukan',
		'pin-login-placeholder': 'Masukkan PIN untuk membuka',
		'pin-login-btn': 'Buka',
		'pin-login-error': 'PIN salah, coba lagi.',
		'pin-login-manual': 'Masukkan kredensial secara manual',
		'pin-login-forget': 'Lupakan dompet tersimpan',
		'saved-wallet-hint-prefix': 'Dompet tersimpan ditemukan. ',
		'saved-wallet-open': 'Buka dengan PIN',
		'saved-wallet-or': ' atau ',
		'saved-wallet-forget': 'lupakan itu',
		'saved-wallet-label': 'Dompet tersimpan',
		'settings-forget-wallet': 'Lupakan dompet tersimpan',
		'pin-title-default': 'PIN Dompet',
		'pin-input-placeholder': 'PIN (min 6 digit)',
		'pin-save-title': 'Simpan dompet',
		'pin-save-desc': 'Masukkan PIN untuk menyimpan dompet. Lain kali Anda hanya perlu PIN untuk membukanya.',
		'pin-create-title': 'Buat PIN dompet',
		'pin-create-desc': 'Pilih PIN (minimal 6 karakter). Anda akan membutuhkannya setiap kali membuka dompet.',
		'pin-confirm-title': 'Konfirmasi PIN',
		'pin-confirm-desc': 'Masukkan ulang PIN Anda untuk konfirmasi.',
		'pin-too-short': 'PIN harus minimal 6 karakter.',
		'pin-mismatch': 'PIN tidak cocok. Coba lagi.',
		'ok': 'OK',
		'coin-control': 'Kontrol Koin',
		'coin-control-manual': 'Pilihan UTXO manual',
		'coin-control-select-all': 'Pilih semua yang matang',
		'coin-control-confs': 'Konf.',
		'coin-control-type': 'Tipe',
		'coin-control-status': 'Status',
		'coin-control-no-utxo': 'Tidak ada UTXO',
		'coin-control-mature': 'matang',
		'coin-control-coinbase': 'coinbase',
		'coin-control-regular': 'reguler',
		'coin-control-matures-in': 'Matang dalam',
		'coin-control-blocks': 'blok',
		'coin-control-immature-title': 'Coinbase belum matang — tidak dapat digunakan',
		'coin-control-selected': 'dipilih',
		'immature-mining': 'Belum matang (mining):',
		'immature-cannot-spend': 'belum bisa digunakan',
		'history-loading': 'Memuat riwayat…',
		'no-transactions': 'Belum ada transaksi',
		'history-failed': 'Gagal memuat riwayat',
		'history-network-error': 'Kesalahan jaringan',
		'history-view-all': 'Lihat semua',
		'history-on-explorer': 'transaksi di explorer',
		'history-conf': 'konf.',
		'history-confirmed': 'dikonfirmasi',
		'history-pending': 'tertunda',
		'copy-address': 'Salin alamat',
		'wallet-saved': 'Dompet disimpan. Lain kali cukup masukkan PIN Anda.',
		'wallet-deleted': 'Dompet tersimpan dihapus.',
		'wallet-corrupted': 'Dompet tersimpan rusak. Silakan buka secara manual.',
		'identity-too-short': 'Identitas harus minimal 3 karakter.',
		'redeem-script': 'Redeem Script (SegWit)'
	},
	'ja': {
		'lang-alias': '日本語',
		'wallet-title': 'ウォレット',
		'open-regular': '通常ウォレット',
		'open-key': 'キーで開く',
		'disclaimer': 'このページではjavascriptを使用してアドレスを生成し、ブラウザ内で取引に署名します。そのため、秘密鍵を送信することはありません。これはGithubのソースコードで確認できます。',
		'open-reminder': '<b>お知らせ:</b> アカウント詳細を忘れないようにしてください。資金にアクセスできなくなる可能性があります。',
		'open': '開く',
		'home': 'ホーム',
		'create': '作成',
		'broadcast': 'ブロードキャスト',
		'settings': '設定',
		'email-address': 'メールアドレス',
		'password': 'パスワード',
		'password-confirm': 'パスワード確認',
		'generate-question': 'まだウォレットをお持ちではありませんか？',
		'generate-it': '<a href="#/create">作ります！</a> ',
		'wif-key': 'WIF形式の秘密鍵',
		'create-wallet': 'ウォレット作成',
		'show': '見る',
		'hide': '隠す',
		'address': 'アドレス',
		'public-key': '公開鍵 (パブリックキー)',
		'private-key': '秘密鍵 (プライベートキー)',
		'broadcast-transaction': '取引のブロードキャスト',
		'enter-transaction': '取引を入力してください',
		'wallet-settings': 'ウォレット設定',
		'address-type': 'アドレス形式',
		'wallet-backend': 'ウォレットバックエンド',
		'update': '更新',
		'wallet-language': 'ウォレット言語',
		'version': 'バージョン:',
		'wallet': 'ウォレット',
		'close': '閉じる',
		'send': '送信',
		'history': '履歴',
		'keys': 'キー',
		'reset': 'リセット',
		'available-balance': '利用可能:',
		'enter-address': 'アドレスを入力してください',
		'amount': '金額',
		'fee': '手数料',
		'recommended': '推奨',
		'loading': '読み込み中...',
		'send-sure': '送信してよろしいですか？',
		'send-processing': '処理中...',
		'success': '成功',
		'failed': '失敗',
		'send-it': 'はい、送信します！',
		'cancel': 'キャンセル',
		'send-warning': '送信まであと少しです。',
		'send-warning-reverse': 'この操作は<strong>取消できません。</strong>本当によろしいですか？',
		'loading-utxo': 'UTXOsを読み込んでいます...',
		'transaction-creation': '取引を作成中...',
		'transaction-broadcasted': '取引のブロードキャストに成功しました: ',
		'close': '閉じる',
		'address-type-changed': 'アドレス形式が次に変更されました',
		'backend-switched': 'バックエンドが次に変更されました',
		'backend-down': 'バックエンド使用不可能',
		'wallet-api': 'ウォレットAPIバックエンド',
		'open-wallet': 'ウォレットを開く',
		'bad-utxo': 'サポートされていないUTXOタイプです！',
		'balance-load-failed': 'ウォレット残高が読み込めませんでした！',
		'not-enough-funds': '取引に対して資金が不足しています',
		'not-valid-address': '正しいアドレスを指定してください！',
		'not-valid-amount': '正しい金額を指定してください！',
		'not-valid-fee': '正しい手数料を指定してください！',
		'bad-priv-key': '秘密鍵が間違っています',
		'not-enough-utxo': 'UTXOが不足しています :(',
		'broadcast-failed': '取引のブロードキャストに失敗しました :(',
		'pass-not-match': 'パスワードが間違っています！',
		'pass-too-short': 'パスワードは10文字以上必要です！',
		'bad-email': 'メールアドレスが登録されていません！',
		'small-fee': '最低手数料は',
		'scan-qr': 'スキャン',
		'scan-modal-title': 'QRコードリーダー',
		'webcam-message': 'ウェブカメラが有効か確認してください',
		'webcam-loading': 'カメラ読み込み中...',
		'outputs-added': '出力に追加',
		'pin-login-title': '保存されたウォレットが見つかりました',
		'pin-login-placeholder': 'PINを入力して開く',
		'pin-login-btn': '開く',
		'pin-login-error': 'PINが間違っています。再入力してください。',
		'pin-login-manual': '手動で認証情報を入力',
		'pin-login-forget': '保存されたウォレットを忘れる',
		'saved-wallet-hint-prefix': '保存されたウォレットが見つかりました。 ',
		'saved-wallet-open': 'PINで開く',
		'saved-wallet-or': ' または ',
		'saved-wallet-forget': '忘れる',
		'saved-wallet-label': '保存されたウォレット',
		'settings-forget-wallet': '保存されたウォレットを忘れる',
		'pin-title-default': 'ウォレットPIN',
		'pin-input-placeholder': 'PIN（6桁以上）',
		'pin-save-title': 'ウォレットを保存',
		'pin-save-desc': 'ウォレットを保存するPINを入力してください。次回からはPINだけで開けます。',
		'pin-create-title': 'ウォレットPINの作成',
		'pin-create-desc': 'PINを設定してください（最低6文字）。ウォレットを開くたびに使用します。',
		'pin-confirm-title': 'PINの確認',
		'pin-confirm-desc': '確認のためPINを再入力してください。',
		'pin-too-short': 'PINは6文字以上必要です。',
		'pin-mismatch': 'PINが一致しません。もう一度試してください。',
		'ok': 'OK',
		'coin-control': 'コインコントロール',
		'coin-control-manual': 'UTXO手動選択',
		'coin-control-select-all': '成熟済みをすべて選択',
		'coin-control-confs': '確認数',
		'coin-control-type': '種類',
		'coin-control-status': '状態',
		'coin-control-no-utxo': 'UTXOなし',
		'coin-control-mature': '使用可',
		'coin-control-coinbase': 'コインベース',
		'coin-control-regular': '通常',
		'coin-control-matures-in': '成熟まで',
		'coin-control-blocks': 'ブロック',
		'coin-control-immature-title': '未成熟なコインベース — 使用不可',
		'coin-control-selected': '選択済み',
		'immature-mining': '未成熟 (マイニング):',
		'immature-cannot-spend': 'まだ使用できません',
		'history-loading': '履歴を読み込み中…',
		'no-transactions': 'トランザクションはまだありません',
		'history-failed': '履歴の読み込みに失敗しました',
		'history-network-error': 'ネットワークエラー',
		'history-view-all': 'すべての',
		'history-on-explorer': 'トランザクションをエクスプローラーで表示',
		'history-conf': '確認',
		'history-confirmed': '確認済み',
		'history-pending': '保留中',
		'copy-address': 'アドレスをコピー',
		'wallet-saved': 'ウォレットを保存しました。次回はPINを入力するだけです。',
		'wallet-deleted': '保存されたウォレットを削除しました。',
		'wallet-corrupted': '保存されたウォレットが破損しています。手動で開いてください。',
		'identity-too-short': 'IDは3文字以上必要です。',
		'redeem-script': 'リデームスクリプト (SegWit)'
	},
	'zh': {
		'lang-alias': '简体中文',
		'wallet-title': '网页钱包',
		'open-regular': '普通钱包',
		'open-key': '密钥钱包',
		'disclaimer': '此页面通过javascript脚本在浏览器中生成地址并为交易签名，这意味着我们不会并且无法保存您的私钥，您可通过我们公布在Github上的源码来验证相关内容的有效性.',
		'open-reminder': '<b>提醒:</b> 请务必记住您的帐户详细信息，否则您可能无法使用您的资金。',
		'open': '打开',
		'home': '首页',
		'create': '创建',
		'broadcast': '广播',
		'settings': '设置',
		'email-address': '邮箱地址',
		'password': '密码',
		'password-confirm': '确认密码',
		'generate-question': '还未拥有钱包吗?',
		'generate-it': '<a href="#/create">创建一个</a>!',
		'wif-key': 'WIF私钥',
		'create-wallet': '创建钱包',
		'show': '显示',
		'hide': '隐藏',
		'address': '地址',
		'public-key': '公钥',
		'private-key': '私钥',
		'broadcast-transaction': '广播交易',
		'enter-transaction': '输入交易签名',
		'wallet-settings': '钱包设置',
		'address-type': '地址类型',
		'wallet-backend': '钱包接口',
		'update': '更新',
		'wallet-language': '钱包语言',
		'version': '版本:',
		'wallet': '钱包',
		'close': '关闭',
		'send': '发送',
		'history': '历史',
		'keys': '密钥',
		'reset': '重置',
		'available-balance': '可用余额:',
		'enter-address': '输入地址',
		'amount': '数量',
		'fee': '交易费用',
		'recommended': '推荐',
		'loading': '加载中...',
		'send-sure': '你确定吗?',
		'send-processing': '处理中...',
		'success': '成功',
		'failed': '失败',
		'send-it': '确定，发送!',
		'cancel': '取消',
		'send-warning': '离交易发送仅一步之遥',
		'send-warning-reverse': '此操作<strong>不可逆转</strong>，你确定吗?',
		'loading-utxo': '加载UTXO中...',
		'transaction-creation': '创建交易中...',
		'transaction-broadcasted': '交易已成功广播: ',
		'close': '关闭',
		'address-type-changed': '地址类型切换至',
		'backend-switched': '后端接口已切换至',
		'backend-down': '似乎不可用',
		'wallet-api': '钱包API接口',
		'open-wallet': '打开钱包',
		'bad-utxo': '不支持的UTXO类型!',
		'balance-load-failed': '钱包可用余额加载失败!',
		'not-enough-funds': '可用余额不足以支持本次交易!',
		'not-valid-address': '请使用有效的钱包地址!',
		'not-valid-amount': '请使用有效的数量!',
		'not-valid-fee': '请指定有效的手续费用金额!',
		'bad-priv-key': '错误的WIF私钥!',
		'not-enough-utxo': '没有足够的UTXO :(',
		'broadcast-failed': '交易广播失败 :(',
		'pass-not-match': '两次输入的密码不匹配!',
		'pass-too-short': '密码不能少于10个字符!',
		'bad-email': '请使用有效的电子邮件格式!',
		'small-fee': '手续费金额不能低于',
		'scan-qr': '扫描',
		'scan-modal-title': 'QR扫描器',
		'webcam-message': '请确保摄像头已启用',
		'webcam-loading': '摄像头加载中...',
		'outputs-added': '已添加到输出',
		'pin-login-title': '发现已保存的钱包',
		'pin-login-placeholder': '输入PIN以打开',
		'pin-login-btn': '打开',
		'pin-login-error': 'PIN错误，请重试。',
		'pin-login-manual': '手动输入凭据',
		'pin-login-forget': '忘记已保存的钱包',
		'saved-wallet-hint-prefix': '发现已保存的钱包。 ',
		'saved-wallet-open': '使用PIN打开',
		'saved-wallet-or': ' 或 ',
		'saved-wallet-forget': '忘记它',
		'saved-wallet-label': '已保存的钱包',
		'settings-forget-wallet': '忘记已保存的钱包',
		'pin-title-default': '钱包PIN',
		'pin-input-placeholder': 'PIN（最少6位）',
		'pin-save-title': '保存钱包',
		'pin-save-desc': '输入PIN以保存钱包。下次只需PIN即可打开。',
		'pin-create-title': '创建钱包PIN',
		'pin-create-desc': '设置PIN（最少6位）。每次打开钱包时需要使用。',
		'pin-confirm-title': '确认PIN',
		'pin-confirm-desc': '请再次输入PIN以确认。',
		'pin-too-short': 'PIN至少需要6位字符。',
		'pin-mismatch': 'PIN不匹配，请重试。',
		'ok': '确定',
		'coin-control': '币控',
		'coin-control-manual': '手动选择UTXO',
		'coin-control-select-all': '选择所有成熟的',
		'coin-control-confs': '确认',
		'coin-control-type': '类型',
		'coin-control-status': '状态',
		'coin-control-no-utxo': '没有UTXO',
		'coin-control-mature': '成熟',
		'coin-control-coinbase': '矿币',
		'coin-control-regular': '普通',
		'coin-control-matures-in': '成熟还需',
		'coin-control-blocks': '个区块',
		'coin-control-immature-title': '未成熟矿币 — 无法使用',
		'coin-control-selected': '已选',
		'immature-mining': '未成熟（挖矿）:',
		'immature-cannot-spend': '暂不可用',
		'history-loading': '加载历史中…',
		'no-transactions': '暂无交易',
		'history-failed': '加载历史失败',
		'history-network-error': '网络错误',
		'history-view-all': '查看全部',
		'history-on-explorer': '笔交易（在浏览器中）',
		'history-conf': '确认',
		'history-confirmed': '已确认',
		'history-pending': '待处理',
		'copy-address': '复制地址',
		'wallet-saved': '钱包已保存。下次只需输入PIN即可。',
		'wallet-deleted': '已保存的钱包已删除。',
		'wallet-corrupted': '已保存的钱包已损坏，请手动重新打开。',
		'identity-too-short': '身份标识至少需要3个字符。',
		'redeem-script': '赎回脚本 (SegWit)'
	},
	'es': {
		'lang-alias': 'Español',
		'wallet-title': 'Cartera',
		'open-regular': 'Cartera regular',
		'open-key': 'Abrir con llave',
		'disclaimer': 'Esta página utiliza Javascript para generar sus direcciones y firmar sus transacciones en su navegador, Esto implica que nunca recibimos sus claves privada, Esto puede ser verificado independientemente por medio de la revisión el código de fuente en Github.',
		'open-reminder': '<b>Aviso:</b> Por favor asegúrese que se acuerda sus detalles de cuenta, podría perder el acceso de los fondos',
		'open': 'Abrir',
		'home': 'Página Inicial',
		'create': 'Crear',
		'broadcast': 'Transmitir',
		'settings': 'Configuraciones',
		'email-address': 'Correo electrónico',
		'password': 'Contraseña',
		'password-confirm': 'Confirma la contraseña',
		'generate-question': 'todavia no tienes cartera?',
		'generate-it': '<a href="#/crear">Generate</a> lo!',
		'wif-key': 'WIF Clave privada',
		'create-wallet': 'Crear cartera',
		'show': 'Mostrar',
		'hide': 'Esconder',
		'address': 'Dirección',
		'public-key': 'Clave pública',
		'private-key': 'Clave privada',
		'broadcast-transaction': 'Transmitir transacción',
		'enter-transaction': 'Introduzca sus transaccion firmado',
		'wallet-settings': 'Configuración de la cartera',
		'address-type': 'Tipo de dirección',
		'wallet-backend': 'Cartera Backend',
		'update': 'Actualización',
		'wallet-language': 'Language de la cartera',
		'version': 'Versión:',
		'wallet': 'Cartera',
		'close': 'Cerrar',
		'send': 'Enviar',
		'history': 'historia',
		'keys': 'Llaves',
		'reset': 'Reiniciar',
		'available-balance': 'Saldo disponible:',
		'enter-address': 'Introduce dirección',
		'amount': 'Cantidad',
		'fee': 'Cuota',
		'recommended': 'recomendado',
		'loading': 'Cargando...',
		'send-sure': '¿Estás seguro?',
		'send-processing': 'Procesamiento...',
		'success': 'éxito',
		'failed': 'falló',
		'send-it': 'sí, envíalo!',
		'cancel': 'Cancelo',
		'send-warning': 'Estás a un paso de envío',
		'send-warning-reverse': 'esta acción <strong>no puede</strong> ser revertida. ¿Estás seguro de esto?',
		'loading-utxo': 'Cargando UTXOs...',
		'transaction-creation': 'Creación de transacción...',
		'transaction-broadcasted': 'Transacción transmitida con éxito: ',
		'close': 'Cerrar',
		'address-type-changed': 'Tipo de dirección cambiado a',
		'backend-switched': 'Backend se cambia a',
		'backend-down': 'no parece estar disponible',
		'wallet-api': 'Backend de cartera API',
		'open-wallet': 'Abrir cartera',
		'bad-utxo': 'Tipo UTXO no compatible',
		'balance-load-failed': '¡No pudimos cargar el saldo de la cartera!',
		'not-enough-funds': '¡No tienes suficientes fondos para esta transacción!',
		'not-valid-address': '¡Debe especificar una dirección válida!',
		'not-valid-amount': '¡Debe especificar la cantidad válida!',
		'not-valid-fee': 'Debe especificar válida cuota!',
		'bad-priv-key': 'Mala WIF clave privada!',
		'not-enough-utxo': 'No hay suficiente UTXO :(',
		'broadcast-failed': 'La transacción transmitió fallado :(',
		'pass-not-match': '¡Tus contraseñas no coinciden!',
		'pass-too-short': 'Su contraseña debe tener al menos 10 caracteres!',
		'bad-email': '¡Tu dirección de correo electrónico no parece ser válida!',
		'small-fee': 'Debe especificar fee no menos de',
		'scan-qr': 'Escanear',
		'scan-modal-title': 'Escáner QR',
		'webcam-message': 'Asegúrese de tener una cámara web habilitada',
		'webcam-loading': 'Cargando cámara...',
		'outputs-added': 'agregado a salidas',
		'pin-login-title': 'Cartera guardada encontrada',
		'pin-login-placeholder': 'Ingrese PIN para abrir',
		'pin-login-btn': 'Abrir',
		'pin-login-error': 'PIN incorrecto, intente de nuevo.',
		'pin-login-manual': 'Ingresar credenciales manualmente',
		'pin-login-forget': 'Olvidar cartera guardada',
		'saved-wallet-hint-prefix': 'Cartera guardada encontrada. ',
		'saved-wallet-open': 'Abrir con PIN',
		'saved-wallet-or': ' o ',
		'saved-wallet-forget': 'olvidarlo',
		'saved-wallet-label': 'Cartera guardada',
		'settings-forget-wallet': 'Olvidar cartera guardada',
		'pin-title-default': 'PIN de cartera',
		'pin-input-placeholder': 'PIN (mín. 6 dígitos)',
		'pin-save-title': 'Guardar cartera',
		'pin-save-desc': 'Ingrese un PIN para guardar la cartera. La próxima vez solo necesitará el PIN para abrirla.',
		'pin-create-title': 'Crear PIN de cartera',
		'pin-create-desc': 'Elija un PIN (mínimo 6 caracteres). Lo necesitará cada vez que abra la cartera.',
		'pin-confirm-title': 'Confirmar PIN',
		'pin-confirm-desc': 'Vuelva a ingresar su PIN para confirmar.',
		'pin-too-short': 'El PIN debe tener al menos 6 caracteres.',
		'pin-mismatch': 'Los PIN no coinciden. Inténtelo de nuevo.',
		'ok': 'Aceptar',
		'coin-control': 'Control de monedas',
		'coin-control-manual': 'Selección manual de UTXO',
		'coin-control-select-all': 'Seleccionar todos los maduros',
		'coin-control-confs': 'Confs.',
		'coin-control-type': 'Tipo',
		'coin-control-status': 'Estado',
		'coin-control-no-utxo': 'Sin UTXO',
		'coin-control-mature': 'maduro',
		'coin-control-coinbase': 'coinbase',
		'coin-control-regular': 'regular',
		'coin-control-matures-in': 'Madura en',
		'coin-control-blocks': 'bloques',
		'coin-control-immature-title': 'Coinbase inmaduro — no se puede gastar',
		'coin-control-selected': 'seleccionado',
		'immature-mining': 'Inmaduro (minería):',
		'immature-cannot-spend': 'aún no se puede gastar',
		'history-loading': 'Cargando historial…',
		'no-transactions': 'Aún no hay transacciones',
		'history-failed': 'Error al cargar el historial',
		'history-network-error': 'Error de red',
		'history-view-all': 'Ver todas las',
		'history-on-explorer': 'transacciones en el explorador',
		'history-conf': 'conf.',
		'history-confirmed': 'confirmado',
		'history-pending': 'pendiente',
		'copy-address': 'Copiar dirección',
		'wallet-saved': 'Cartera guardada. La próxima vez solo ingresa tu PIN.',
		'wallet-deleted': 'Cartera guardada eliminada.',
		'wallet-corrupted': 'La cartera guardada está corrupta. Por favor, ábrela manualmente.',
		'identity-too-short': 'La identidad debe tener al menos 3 caracteres.',
		'redeem-script': 'Redeem Script (SegWit)'
	},
	'ru': {
		'lang-alias': 'Русский',
		'wallet-title': 'Кошелек',
		'open-regular': 'Обычный кошелек',
		'open-key': 'Открыть ключом',
		'disclaimer': 'Эта страница использует javascript для генерации Вашего адреса и подписи Ваших транзакциий внутри браузера, это значит, что мы никогда не получаем Ваши приватные ключи, и это можно независимо проверить, прочитав исходный код на GitHub.',
		'open-reminder': '<b>Внимание:</b> Пожалуйста убедитесь, что Вы запомнили детали вашего аккаунта, иначе Вы можете потерять доступ к своим денежным средствам.',
		'open': 'Открыть',
		'home': 'Домой',
		'create': 'Создать',
		'broadcast': 'Транслировать',
		'settings': 'Настройки',
		'email-address': 'Электронная почта',
		'password': 'Пароль',
		'password-confirm': 'Подтвердить пароль',
		'generate-question': 'Всё еще нету кошелька?',
		'generate-it': '<a href="#/create">Сгенерировать</a> его!',
		'wif-key': 'Приватный ключ WIF',
		'create-wallet': 'Создать кошелек',
		'show': 'Показать',
		'hide': 'Спрятать',
		'address': 'Адрес',
		'public-key': 'Публичный Ключ',
		'private-key': 'Приватный Ключ',
		'broadcast-transaction': 'Транслировать транзакцию',
		'enter-transaction': 'Введите Вашу подписанную транзакцию',
		'wallet-settings': 'Настройки кошелька',
		'address-type': 'Тип Адреса',
		'wallet-backend': 'Бэкэнд Кошелька',
		'update': 'Обновить',
		'wallet-language': 'Язык Кошелька',
		'version': 'Версия:',
		'wallet': 'Кошелек',
		'close': 'Закрыть',
		'send': 'Отправить',
		'history': 'История',
		'keys': 'Ключи',
		'reset': 'Сбросить',
		'available-balance': 'Доступный баланс:',
		'enter-address': 'Введите адрес',
		'amount': 'Сумма',
		'fee': 'Комиссия',
		'recommended': 'рекомендовано',
		'loading': 'Загрузка...',
		'send-sure': 'Вы уверены?',
		'send-processing': 'Обработка...',
		'success': 'Успех',
		'failed': 'Неудача',
		'send-it': 'Да, отправить!',
		'cancel': 'Отменить',
		'send-warning': 'Вы в одном шаге от того, чтобы отправить',
		'send-warning-reverse': 'Это действие <strong>не может</strong> быть отменено. Вы в этом уверены?',
		'loading-utxo': 'Загрузка UTXOs...',
		'transaction-creation': 'Создание транзакции...',
		'transaction-broadcasted': 'Транзакция успешна транслирована: ',
		'close': 'Закрыть',
		'address-type-changed': 'Тип адреса изменен на',
		'backend-switched': 'Бэкэнд изменен на',
		'backend-down': 'не доступен',
		'wallet-api': 'API бэкэнд кошелька',
		'open-wallet': 'Открыть Кошелек',
		'bad-utxo': 'Неподдерживаемый тип UTXO!',
		'balance-load-failed': 'Мы не можем загрузить баланс кошелька!',
		'not-enough-funds': 'У Вас недостаточно денежных средств для этой транзакции!',
		'not-valid-address': 'Вы должны указать действительный адрес!',
		'not-valid-amount': 'Вы должны указать действительную сумму!',
		'not-valid-fee': 'Вы должны указать действительную комиссию!',
		'bad-priv-key': 'Неверный приватный ключ WIF!',
		'not-enough-utxo': 'Недостаточно UTXO :(',
		'broadcast-failed': 'Не удалось транслировать транзакцию :(',
		'pass-not-match': 'Ваши пароли не совпадают!',
		'pass-too-short': 'Ваш пароль должен быть не меньше 10 символов!',
		'bad-email': 'Похоже, Вы ввели не действительный электронный адрес!',
		'small-fee': 'Вы должны указать комиссию не меньше, чем',
		'scan-qr': 'Сканировать',
		'scan-modal-title': 'Сканер QR-кода',
		'webcam-message': 'Убедитесь, что веб-камера включена',
		'webcam-loading': 'Загрузка камеры...',
		'outputs-added': 'добавлен в выходы',
		'pin-login-title': 'Найден сохраненный кошелек',
		'pin-login-placeholder': 'Введите PIN для открытия',
		'pin-login-btn': 'Открыть',
		'pin-login-error': 'Неверный PIN, попробуйте снова.',
		'pin-login-manual': 'Ввести данные вручную',
		'pin-login-forget': 'Забыть сохраненный кошелек',
		'saved-wallet-hint-prefix': 'Найден сохраненный кошелек. ',
		'saved-wallet-open': 'Открыть с PIN',
		'saved-wallet-or': ' или ',
		'saved-wallet-forget': 'забыть его',
		'saved-wallet-label': 'Сохраненный кошелек',
		'settings-forget-wallet': 'Забыть сохраненный кошелек',
		'pin-title-default': 'PIN кошелька',
		'pin-input-placeholder': 'PIN (мин. 6 цифры)',
		'pin-save-title': 'Сохранить кошелек',
		'pin-save-desc': 'Введите PIN, чтобы сохранить кошелек. В следующий раз вам понадобится только PIN для входа.',
		'pin-create-title': 'Создать PIN кошелька',
		'pin-create-desc': 'Придумайте PIN (минимум 6 символов). Он понадобится каждый раз при открытии кошелька.',
		'pin-confirm-title': 'Подтвердить PIN',
		'pin-confirm-desc': 'Введите PIN ещё раз для подтверждения.',
		'pin-too-short': 'PIN должен содержать не менее 6 символов.',
		'pin-mismatch': 'PIN-коды не совпадают. Попробуйте ещё раз.',
		'ok': 'ОК',
		'coin-control': 'Контроль монет',
		'coin-control-manual': 'Ручной выбор UTXO',
		'coin-control-select-all': 'Выбрать все зрелые',
		'coin-control-confs': 'Подтв.',
		'coin-control-type': 'Тип',
		'coin-control-status': 'Статус',
		'coin-control-no-utxo': 'Нет UTXO',
		'coin-control-mature': 'зрелый',
		'coin-control-coinbase': 'coinbase',
		'coin-control-regular': 'обычный',
		'coin-control-matures-in': 'Созреет через',
		'coin-control-blocks': 'блоков',
		'coin-control-immature-title': 'Незрелый coinbase — нельзя потратить',
		'coin-control-selected': 'выбрано',
		'immature-mining': 'Незрелый (майнинг):',
		'immature-cannot-spend': 'пока нельзя потратить',
		'history-loading': 'Загрузка истории…',
		'no-transactions': 'Транзакций пока нет',
		'history-failed': 'Не удалось загрузить историю',
		'history-network-error': 'Ошибка сети',
		'history-view-all': 'Посмотреть все',
		'history-on-explorer': 'транзакций в обозревателе',
		'history-conf': 'подтв.',
		'history-confirmed': 'подтверждено',
		'history-pending': 'ожидание',
		'copy-address': 'Скопировать адрес',
		'wallet-saved': 'Кошелёк сохранён. В следующий раз просто введите PIN.',
		'wallet-deleted': 'Сохранённый кошелёк удалён.',
		'wallet-corrupted': 'Сохранённый кошелёк повреждён. Пожалуйста, откройте вручную.',
		'identity-too-short': 'Идентификатор должен содержать не менее 3 символов.',
		'redeem-script': 'Скрипт погашения (SegWit)'
	},
	'kr': {
		'lang-alias': '한국어',
		'wallet-title': '지갑',
		'open-regular': '일반 지갑',
		'open-key': '개인키로 열기',
		'disclaimer': '이 페이지는 javascript를 사용하여 주소를 생성하고 브라우저 내에서 거래에 서명합니다. 즉, 개인키를 절대 받지 않습니다. Github 소스 코드를 통하여 이를 검토할 수 있습니다.',
		'open-reminder': '<b>알림:</b> 계좌 정보를 안전하게 보관해주세요. 그렇지 않으면 코인을 영원히 잃을 수 있습니다.',
		'open': '열기',
		'home': '홈',
		'create': '생성',
		'broadcast': '브로드캐스트',
		'settings': '설정',
		'email-address': '메일 주소',
		'password': '비밀번호',
		'password-confirm': '비밀번호 확인',
		'generate-question': '아직 지갑이 없으신가요?',
		'generate-it': '<a href="#/create">생성하러 가기!</a>',
		'wif-key': 'WIF 개인키',
		'create-wallet': '지갑 생성하기',
		'show': '표시하기',
		'hide': '숨기기',
		'address': '주소',
		'public-key': '공개키',
		'private-key': '개인키',
		'broadcast-transaction': '거래 브로드캐스트',
		'enter-transaction': '서명된 거래를 입력해주세요.',
		'wallet-settings': '지갑 설정',
		'address-type': '주소 형식',
		'wallet-backend': '지갑 백앤드',
		'update': '갱신',
		'wallet-language': '지갑 언어',
		'version': '버전:',
		'wallet': '지갑',
		'close': '닫기',
		'send': '보내기',
		'history': '거래내역',
		'keys': '지갑키',
		'reset': '초기화',
		'available-balance': '이용 가능한 잔액:',
		'enter-address': '주소 입력',
		'amount': '전송량',
		'fee': '수수료',
		'recommended': '추천',
		'loading': '로드중...',
		'send-sure': '전송하시겠습니까?',
		'send-processing': '처리중...',
		'success': '성공',
		'failed': '실패',
		'send-it': '정상적으로 전송되었습니다!',
		'cancel': '취소',
		'send-warning': '다음과 같이 전송하고자 합니다',
		'send-warning-reverse': '이 작업을 시도하면 <strong>취소할 수 없습니다.</strong> 삭제 하시겠습니까?',
		'loading-utxo': 'UTXOs 로드중...',
		'transaction-creation': '거래 생성 중...',
		'transaction-broadcasted': '거래 브로드캐스트 성공: ',
		'close': '닫기',
		'address-type-changed': '정상적으로 주소 형식이 변경되었습니다.',
		'backend-switched': '정상적으로 백앤드가 변경되었습니다.',
		'backend-down': '사용할 수 없는 백앤드 입니다.',
		'wallet-api': '지갑 API 백앤드',
		'open-wallet': '지갑 열기',
		'bad-utxo': '지원되지 않는 UTXO 형식 입니다.',
		'balance-load-failed': '지갑 잔액 불러오기 실패!',
		'not-enough-funds': '전송에 필요한 잔액이 부족합니다.',
		'not-valid-address': '올바른 지갑 주소가 아닙니다.',
		'not-valid-amount': '올바른 전송량이 아닙니다.',
		'not-valid-fee': '올바른 수수료가 아닙니다.',
		'bad-priv-key': '잘못된 WIF개인키 입니다.',
		'not-enough-utxo': 'UTXO이 부족합니다. :(',
		'broadcast-failed': '거래 브로드캐스트에 실패하였습니다. :(',
		'pass-not-match': '비밀번호가 일치하지 않습니다.',
		'pass-too-short': '비밀번호는 10글자 이상 입력해주세요.',
		'bad-email': '올바른 메일 주소가 아닙니다.',
		'small-fee': '최소수수료',
		'scan-qr': '스캔',
		'scan-modal-title': 'QR 코드 스캐너',
		'webcam-message': '웹캠이 활성화되었는지 확인하세요',
		'webcam-loading': '카메라 로딩 중...',
		'outputs-added': '출력에 추가됨',
		'pin-login-title': '저장된 지갑을 찾았습니다',
		'pin-login-placeholder': 'PIN을 입력하여 열기',
		'pin-login-btn': '열기',
		'pin-login-error': 'PIN이 틀렸습니다. 다시 시도하세요.',
		'pin-login-manual': '직접 자격 증명 입력',
		'pin-login-forget': '저장된 지갑 삭제',
		'saved-wallet-hint-prefix': '저장된 지갑을 찾았습니다. ',
		'saved-wallet-open': 'PIN으로 열기',
		'saved-wallet-or': ' 또는 ',
		'saved-wallet-forget': '지우기',
		'saved-wallet-label': '저장된 지갑',
		'settings-forget-wallet': '저장된 지갑 삭제',
		'pin-title-default': '지갑 PIN',
		'pin-input-placeholder': 'PIN (최소 6자리)',
		'pin-save-title': '지갑 저장',
		'pin-save-desc': '지갑을 저장할 PIN을 입력하세요. 다음에는 PIN만으로 열 수 있습니다.',
		'pin-create-title': '지갑 PIN 만들기',
		'pin-create-desc': 'PIN을 선택하세요 (최소 6자). 지갑을 열 때마다 사용됩니다.',
		'pin-confirm-title': 'PIN 확인',
		'pin-confirm-desc': '확인을 위해 PIN을 다시 입력하세요.',
		'pin-too-short': 'PIN은 최소 6자 이상이어야 합니다.',
		'pin-mismatch': 'PIN이 일치하지 않습니다. 다시 시도하세요.',
		'ok': '확인',
		'coin-control': '코인 제어',
		'coin-control-manual': '수동 UTXO 선택',
		'coin-control-select-all': '성숙한 항목 모두 선택',
		'coin-control-confs': '확인수',
		'coin-control-type': '유형',
		'coin-control-status': '상태',
		'coin-control-no-utxo': 'UTXO 없음',
		'coin-control-mature': '사용 가능',
		'coin-control-coinbase': '코인베이스',
		'coin-control-regular': '일반',
		'coin-control-matures-in': '성숙까지',
		'coin-control-blocks': '블록',
		'coin-control-immature-title': '미성숙 코인베이스 — 사용 불가',
		'coin-control-selected': '선택됨',
		'immature-mining': '미성숙 (채굴):',
		'immature-cannot-spend': '아직 사용할 수 없음',
		'history-loading': '내역 로딩 중…',
		'no-transactions': '거래 내역이 없습니다',
		'history-failed': '내역 로드 실패',
		'history-network-error': '네트워크 오류',
		'history-view-all': '모든',
		'history-on-explorer': '거래 내역 보기 (탐색기)',
		'history-conf': '확인',
		'history-confirmed': '확인됨',
		'history-pending': '대기 중',
		'copy-address': '주소 복사',
		'wallet-saved': '지갑이 저장되었습니다. 다음에는 PIN만 입력하세요.',
		'wallet-deleted': '저장된 지갑이 삭제되었습니다.',
		'wallet-corrupted': '저장된 지갑이 손상되었습니다. 수동으로 다시 열어주세요.',
		'identity-too-short': '신원은 최소 3자 이상이어야 합니다.',
		'redeem-script': '리딤 스크립트 (SegWit)'
	},
	'de': {
		'lang-alias': 'Deutsch',
		'wallet-title': 'Wallet',
		'open-regular': 'Reguläre Wallet',
		'open-key': 'Mit Schlüssel öffnen',
		'disclaimer': 'Dieses Wallet benutzt JavaScript um Deine Adressen zu generieren und Transaktionen im Browser zu signieren. Zu keinem Zeitpunkt wird hierbei dein Privatschlüssel dauerhaft gespeichert!! Zur Überprüfung kann der Quellcode jederzeit im GitHub eingesehen werden.',
		'open-reminder': '<b>Notice:</b> Sorge bitte dafür dich an deine Kontodaten erinnern zu können um nicht den Zugriff zu deinem Konto und dessen Guthaben zu verlieren!',
		'open': 'Öffnen',
		'home': 'Startseite',
		'create': 'Erstellen',
		'broadcast': 'Übertragung',
		'settings': 'Einstellungen',
		'email-address': 'Email Addresse',
		'password': 'Passwort',
		'password-confirm': 'Passwort bestätigen',
		'generate-question': 'Du hast noch keine Wallet',
		'generate-it': '<a href="#/create">Hier Wallet erstellen</a> it!',
		'wif-key': 'Privater Schlüssel (WIF)',
		'create-wallet': 'Wallet erstellen',
		'show': 'Anzeigen',
		'hide': 'Verbergen',
		'address': 'Addresse',
		'public-key': 'Öffentlicher Schlüssel',
		'private-key': 'Privater Schlüssel',
		'broadcast-transaction': 'Transaktion senden',
		'enter-transaction': 'Signierte Transaktion eintragen',
		'wallet-settings': 'Wallet-Einstellungen',
		'address-type': 'Addresstyp',
		'wallet-backend': 'Wallet Backend',
		'update': 'Aktualisieren',
		'wallet-language': 'Wallet Sprachwahl',
		'version': 'Version:',
		'wallet': 'Wallet',
		'close': 'Schließen',
		'send': 'Senden',
		'history': 'Verlauf',
		'keys': 'Schlüssel',
		'reset': 'Reset',
		'available-balance': 'Verfügbares Guthaben:',
		'enter-address': 'Adresse eingeben',
		'amount': 'Betrag',
		'fee': 'Transaktionsgebühr',
		'recommended': 'empfohlen',
		'loading': 'Lade...',
		'send-sure': 'Bist du sicher?',
		'send-processing': 'Verarbeitung läuft...',
		'success': 'Aktion erfolgreich',
		'failed': 'Aktion fehlgeschlagen',
		'send-it': 'Ja, bitte senden!',
		'cancel': 'Abbruch',
		'send-warning': 'Du bist dabei, eine Zahlung zu senden',
		'send-warning-reverse': 'Diese Aktion kann<strong>nicht rückgängig</strong> gemacht werden. Bist Du wirklich sicher?',
		'loading-utxo': 'Lade UTXOen...',
		'transaction-creation': 'Transaktion wird erstellt...',
		'transaction-broadcasted': 'Transaktion erfolgreich gesendet: ',
		'close': 'Schließen',
		'address-type-changed': 'Adresstyp geändert in',
		'backend-switched': 'Backend geändert zu',
		'backend-down': 'scheint gerade nicht verfügbar zu sein',
		'wallet-api': 'Wallet API backend',
		'open-wallet': 'Wallet öffnen',
		'bad-utxo': 'Nicht unterstützter UTXO Typ!',
		'balance-load-failed': 'Kontostand konnte nicht geladen werden!',
		'not-enough-funds': 'Dein Guthaben ist für diese Transaktion nicht ausreichend!',
		'not-valid-address': 'Bitte gib eine gültige Adresse ein!',
		'not-valid-amount': 'Bitte gib einen gültigen Betrag ein!',
		'not-valid-fee': 'Bitte gib eine gültige Transaktionsgebühr ein!',
		'bad-priv-key': 'Ungültiger oder falscher WIF-Schlüssel',
		'not-enough-utxo': 'Nicht genügend UTXO :(',
		'broadcast-failed': 'Sendung der Transaktion fehlgeschlagen :(',
		'pass-not-match': 'Die von Dir eingegebenen Passwörter stimmen nicht überein!',
		'pass-too-short': 'Die Länge Deines Passworts muss mindestens 10 Zeichen betragen!',
		'bad-email': 'Deine Email-Adresse scheint nicht gültig zu sein!',
		'small-fee': 'sollte nicht weniger betragen als',
		'scan-qr': 'Scannen',
		'scan-modal-title': 'QR-Code-Scanner',
		'webcam-message': 'Bitte stellen Sie sicher, dass eine Webcam aktiviert ist',
		'webcam-loading': 'Kamera wird geladen...',
		'outputs-added': 'zu Ausgängen hinzugefügt',
		'pin-login-title': 'Gespeicherte Wallet gefunden',
		'pin-login-placeholder': 'PIN zum Öffnen eingeben',
		'pin-login-btn': 'Öffnen',
		'pin-login-error': 'Falsche PIN, erneut versuchen.',
		'pin-login-manual': 'Anmeldedaten manuell eingeben',
		'pin-login-forget': 'Gespeicherte Wallet vergessen',
		'saved-wallet-hint-prefix': 'Gespeicherte Wallet gefunden. ',
		'saved-wallet-open': 'Mit PIN öffnen',
		'saved-wallet-or': ' oder ',
		'saved-wallet-forget': 'vergessen',
		'saved-wallet-label': 'Gespeicherte Wallet',
		'settings-forget-wallet': 'Gespeicherte Wallet vergessen',
		'pin-title-default': 'Wallet-PIN',
		'pin-input-placeholder': 'PIN (mind. 6-stellig)',
		'pin-save-title': 'Wallet speichern',
		'pin-save-desc': 'Gib eine PIN ein, um die Wallet zu speichern. Nächstes Mal benötigst du nur die PIN.',
		'pin-create-title': 'Wallet-PIN erstellen',
		'pin-create-desc': 'Wähle eine PIN (mindestens 6 Zeichen). Du benötigst sie jedes Mal beim Öffnen der Wallet.',
		'pin-confirm-title': 'PIN bestätigen',
		'pin-confirm-desc': 'Gib deine PIN zur Bestätigung erneut ein.',
		'pin-too-short': 'Die PIN muss mindestens 6 Zeichen lang sein.',
		'pin-mismatch': 'Die PINs stimmen nicht überein. Versuche es erneut.',
		'ok': 'OK',
		'coin-control': 'Münzkontrolle',
		'coin-control-manual': 'Manuelle UTXO-Auswahl',
		'coin-control-select-all': 'Alle reifen auswählen',
		'coin-control-confs': 'Best.',
		'coin-control-type': 'Typ',
		'coin-control-status': 'Status',
		'coin-control-no-utxo': 'Keine UTXOs',
		'coin-control-mature': 'reif',
		'coin-control-coinbase': 'Coinbase',
		'coin-control-regular': 'regulär',
		'coin-control-matures-in': 'Reift in',
		'coin-control-blocks': 'Blöcken',
		'coin-control-immature-title': 'Unreifer Coinbase — kann nicht ausgegeben werden',
		'coin-control-selected': 'ausgewählt',
		'immature-mining': 'Unreif (Mining):',
		'immature-cannot-spend': 'noch nicht ausgebbar',
		'history-loading': 'Verlauf wird geladen…',
		'no-transactions': 'Noch keine Transaktionen',
		'history-failed': 'Verlauf konnte nicht geladen werden',
		'history-network-error': 'Netzwerkfehler',
		'history-view-all': 'Alle',
		'history-on-explorer': 'Transaktionen im Explorer anzeigen',
		'history-conf': 'Best.',
		'history-confirmed': 'bestätigt',
		'history-pending': 'ausstehend',
		'copy-address': 'Adresse kopieren',
		'wallet-saved': 'Wallet gespeichert. Beim nächsten Mal reicht die PIN.',
		'wallet-deleted': 'Gespeicherte Wallet gelöscht.',
		'wallet-corrupted': 'Gespeicherte Wallet ist beschädigt. Bitte manuell öffnen.',
		'identity-too-short': 'Die Identität muss mindestens 3 Zeichen lang sein.',
		'redeem-script': 'Einlöseskript (SegWit)'
	}
}
